### ISSUE TITLE
能不能像phpexcel一样实现单元格下拉列表选择的

### ISSUE THREAD

**Issue by leishaofa** [PHPOffice/PhpSpreadsheet#1013]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

**Comment by MarkBaker** [comment]
It's already implemented, and has been for several years, since we ported the original code from PHPExcel: [Documentation](https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#setting-data-validation-on-a-cell) and [Example 1](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Basic/15_Datavalidation.php), [Example 2](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Basic/39_Dropdown.php)

**Comment by leishaofa** [comment]
恩，已经实现了，虽然最后还是参考phpexcel，来找到的PhpSpreadsheet实现方式。可能文档确实没有phpexcel文档说的比较全面




------------------ 原始邮件 ------------------
发件人: "Mark Baker"<notifications@github.com>;
发送时间: 2019年6月17日(星期一) 晚上6:06
收件人: "PHPOffice/PhpSpreadsheet"<PhpSpreadsheet@noreply.github.com>;
抄送: "雷如意"<leishaofa@foxmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [PHPOffice/PhpSpreadsheet] 能不能像phpexcel一样实现单元格下拉列表选择的 (#1013)




It's already implemented, and has been for several years, since we ported the original code from PHPExcel: Documentation and Example 1, Example 2
