### ISSUE TITLE
Using ReadFilter insert null rows

### ISSUE THREAD

**Issue by carl-boisvert** [PHPOffice/PhpSpreadsheet#103]
I've played around with the ReadFilter to read a big csv file line by line. The problem is that the array that is created by the loadIntoExisting function creates a lot of empty rows. I.E. If I want row 20 to 30, the array returned will have row 1 to 20 with null values at each cell, and than 20-30 with the rows that I want.

We could add a parameter to loadIntoExisting to make it possible to remove the empty row. I could do it, just want to get your input on that. Maybe it's the wrong way to use it, but to me, the use case for a filter is to have only certain row returned, but if the array returned contains all previous row with null values, it makes it harder to use.

What do you think?

**Comment by MarkBaker** [comment]
It doesn't actually create empty rows, there's no memory overhead for the cells in these rows because they simply aren't created; it uses the row numbers, and that is very deliberate.... if the file identifies a cell as being A201, then it should be in row 201, and not in row 1. The caveat on this is loading CSV files, which don't have a  an identified row number. Trying to access a cell in that doesn't exist will actually create a cell; but unless you do try to access a cell outside of the readfilter loaded range, then there isn't the memory overhead for that cell.

However, if you want to make that an option, you'll have to consider cell formulae that will need adjusting, and styles, etc so that they are set for the adjusted row numbers.
