### ISSUE TITLE
Infinity loop problem

### ISSUE THREAD

**Issue by ordinaryparksee** [PHPOffice/PhpSpreadsheet#1171]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
IOFactory::load should be work with this file
[error.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/3641081/error.xlsx)

### What is the current behavior?
Some logic is looping or recurse infinitely

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;

$excel = IOFactory::load('./error.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
Maybe up from 1.8.2

**Comment by siarheipashkevich** [comment]
Any updates?

**Comment by darenas31415** [comment]
I've had a look and found that this loop [src/PhpSpreadsheet/Reader/Xlsx.php#L553](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Reader/Xlsx.php#L553) is executed 32739 times which ends up exhausting the memory as every iteration stores the cell style in a parent object.
It's weird because the xlsx file unzipped and converted to xml is 37.9 MB.
I suspect that cells that seem to be empty hold some style metadata.

**Comment by ordinaryparksee** [comment]
thanks for watching
will it be fixed? or decided just excel file problem?

**Comment by darenas31415** [comment]
I'm sorry I'm not the maintainer so I can't decide.

I had a look at the code but I'm not familiar with XLSX format and whether all the cell styles are required to be in memory or not.

The good thing is the library is open source, so you can try to find a solution and improve it :)

Best

**Comment by oleibman** [comment]
The spreadsheet has many duplicate or unneeded styles. The styles.xml member requires 6.71MB, and takes a long time to parse. However, if you just use PhpSpreadsheet to load (takes a while but not infinite) and then save this spreadsheet, styles.xml winds up being reduced to 4,273 bytes, much less than 1/1000th of the original size. So the problem is unique to your spreadsheet, and, if it was generated by PhpSpreadsheet, whatever was causing the duplicate/unneeded entries has been fixed.
