### ISSUE TITLE
Xlsx worksheet toArray nulls issue

### ISSUE THREAD

**Issue by AndorSarig** [PHPOffice/PhpSpreadsheet#1173]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When the readDataOnly is set to true and readEmptyCells to false, the array made from a sheet should contain the rows and columns until the last filled data cells can be found in a column/row.

### What is the current behavior?
When the readDataOnly is set to true and readEmptyCells to false, the array made from a sheet contains dozens of null values in each row (even after the last filled cell).

### What are the steps to reproduce?
Steps to reproduce: See code below.
![image](https://user-images.githubusercontent.com/35924081/65510516-cc67bc80-dedd-11e9-82b5-6d24fce176e9.png)

### Recommendation
\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet:getHighestColumn() function returns wrong column 'index'. As I've seen, the readEmptyCells flag is not taken into consideration during conversion into array.

### Which versions of PhpSpreadsheet and PHP are affected?
PHP Version: 7.2.13
PhpSpreadsheet Version: 1.9

**Comment by siarheipashkevich** [comment]
@AndorSarig I've the same problem. Did you resolve this issue?

**Comment by sbreiler** [comment]
If you trying to get a range of cells, of course you need to put "some" (`null`) value instead of a actual cell value - otherwise you're resulting array will be dissorted. `ReadDataOnly` and `ReadEmptyCells` doesn't do any good in this situation.

It's not clear to me how `toArray` determine the last cell/row. However, if you somehow know the dimensions you want to get, you can use the method `rangeToArray` instead. E.g. using `getHighestDataColumn` and `getHighestDataRow`. If my memory serves me right, even those methods could be wrong if youre excel is cluttered with "empty" cells (i had excel files with just two filled cells, but size was of several megabytes).

```php
// you should name $spreadsheet => $activesheet/$worksheet or something not to get confused
// ReadEmptyCells should be false
$fileContent = $spreadsheet->rangeToArray(
    'A1:' . $spreadsheet->getHighestColumn() . $spreadsheet->getHighestDataRow()
);
```

**Comment by konstantin83** [comment]
Same problem here. Anyone found the cure?

**Comment by MarkBaker** [comment]
The cure is not making assumptions.... `toArray()` determines the highest row/column for a cell based on the data read from the file, and stores that value.... this may be a style reference to a cell, or a print range reference, it is not limited to cells that contain data.

Using `rangeToArray()` requires knowing the highest row/column reference to specify in the range: the `getHighestDataColumn()` and `getHighestDataRow()` methods return the highest column/row that actually contain data, although even that may be a cell containing a null value or an empty string

**Comment by konstantin83** [comment]
Thanks for your answer. But how not to make assumptions, when I had multiple (700+) NULL values in each rows. Setting setReadEmptyCells(false) also didn't help, while obviously it should.
I am writing and reading the same file generated by Phpspreadsheet. So this was pretty strange.

In my case **the cure** is this code in a function which saves xlsx file with phpspreadsheet:
`if (function_exists("mb_internal_encoding")) {
    $oldEncoding = mb_internal_encoding();
    mb_internal_encoding('cp1251');
    $writer->save("php://output");
    mb_internal_encoding($oldEncoding);
} else {
    $writer->save("php://output");
}`

Previously I used **latin1** and got lots of NULL cells. After switching to **cp1251** everything works fine.

**Comment by MarkBaker** [comment]
Depending on the filetype that you're reading, PHPSpreadsheet tries to use UTF-8 throughout... all spreadsheet-native formats have an encoding defined that is converted to UTF-8 by the Reader, The HTML Reader will try to identify a charset for conversion to UTF-8 from the file headers, CSV allows you to specify the encoding, because it can't easily be determined (although PHPSpreadsheet will try to take a guess
When saving, UTF-8 will be used

**Comment by ETNyx** [comment]
Got affected by this issue today,
> ```
> // you should name $spreadsheet => $activesheet/$worksheet or something not to get confused
> // ReadEmptyCells should be false
> $fileContent = $spreadsheet->rangeToArray(
>     'A1:' . $spreadsheet->getHighestColumn() . $spreadsheet->getHighestDataRow()
> );
> ```

this kind of work just getHighestColumn() switched to getHighestDataColumn().
