### ISSUE TITLE
Thousands being readed like decimals

### ISSUE THREAD

**Issue by andoni10war** [PHPOffice/PhpSpreadsheet#1261]
I´m trying to read a number from a formula from an .xlsx file using: 
 $spreadsheet->getActiveSheet()->getCell('T63')->getOldCalculatedValue()

Then, I want to insert that value into mysql database and I can´t for the following reason. For example, if the value of the cell T63 is 1234, getOldCalculatedValue() returns 1,234 , and mysql reads it like a double. So I need to get that value without the comma. Is it any mode to do it?

**Comment by Collie-IT** [comment]
The problem is the number formatting (default is the local style of your country/excel). You can set manual the style  with 
`$spreadsheet->getActiveSheet()->getStyle(''T63)->getNumberFormat()->setFormatCode('#');`
for more Infrmation [see](https://phpoffice.github.io/PhpSpreadsheet/master/PhpOffice/PhpSpreadsheet/Style/NumberFormat.html)

Alternatively you can strip the "," with php replace or regex.

**Comment by andoni10war** [comment]
I´ve tried to do like this but it doesn´t work:
`str_replace(",",".", number_format($spreadsheet->getActiveSheet()->getCell('T63')-> getOldCalculatedValue(), 0));`

I dont´t understand how it works the manual style, could you explain it with an example?

**Comment by MarkBaker** [comment]
`getOldCalculatedValue()` doesn't do any formatting itself, it returns the ___raw___ value that may have been stored for that cell. If that value contains a comma like `1,234`, then the raw value was a string containing that comma and PHPSpreadsheet does not change it in any way
