### ISSUE TITLE
PHP 7.0 and older

### ISSUE THREAD

**Issue by smdimagerie** [PHPOffice/PhpSpreadsheet#1312]
Just an idea here:

I've noticed that the reason of why php 7.0 is not supported is because of the syntax. For me it's problematic because a lot of servers of existing projects do not support php 7.1.

For Exemple
`[$a, $b] = $array;`

could be replaced by
`list($a,$b)`

I've modified a version of the library bug per bug (as I get errors) and got that working on an old server. Maybe you should modify the library to extend usage.

**Comment by MAKS-dev** [comment]
This lib only supports PHP 7.1 and higher, als indicated a few times .. like: [here](https://github.com/PHPOffice/PhpSpreadsheet/issues/1213#issuecomment-548473417) and [here](https://github.com/PHPOffice/PhpSpreadsheet/issues/1189#issuecomment-540090060)

However, I don't see this need myself and already mentioned this [here](https://github.com/PHPOffice/PhpSpreadsheet/issues/1241#issuecomment-553842593).
But, since we don't write the code we can only accept what is given ;-)

**Comment by elieobeid7** [comment]
You can go back in releases here

https://github.com/PHPOffice/PhpSpreadsheet/releases

version 1.8.2 supports php 5.6 every version works perfectly. If you need to support php 5.3 use phpexcel, it works perfect and everything is in it, I had to use it just now because our production servers run php 5.5 and can't be upgraded for reasons outside the scope of this question.

I was able to rollback very fast and nothing changed regarding the generated file itself for real, so awesome.

**Comment by MarkBaker** [comment]
We have a Long Term Support (LTS) policy that means we will ensure that the latest version of PHPSpreadsheet will continue to work with PHP versions for a full 12 months after the EOL of that PHP version.

 - PHP 7.0 was EOL on 10th January 2019, so we supported PHP 7.0 until 10th January 2020.
 - PHP 7.1 was EOL on 1st December 2019, so we will continue to support it until 1st December 2020.

This means that we can't start using any of the new features of PHP 7.4 such as arrow  functions or typed properties until a year after PHP 7.4 End of Life, so it will be 28th November 2022 before we can use those features within the PHPSpreadsheet codebase.

However, it does mean that we can't be shackled into maintaining support for old versions of PHP forever.

Older versions of PHPSpreadsheet are still available, and can be used with versions of PHP prior to 7.1
