### ISSUE TITLE
Chart Reverse Axis on 

### ISSUE THREAD

**Issue by LordKBX** [PHPOffice/PhpSpreadsheet#1399]
When i Try to reverse the Axis with the following code i do not obtain the reverse orientation
`$chart1->getChartAxisX()->setAxisOrientation(Axis::ORIENTATION_REVERSED);`

My Code
[statsExport.txt](https://github.com/PHPOffice/PhpSpreadsheet/files/4268149/statsExport.txt)

**Comment by oleibman** [comment]
I cannot use the supplied program, because the include member which supplies the data is unavailable. However, when I add the supplied statement to 33_Chart_create_bar_custom_colors.php, the result looks correct to me. Seems like whatever the problem was in 2020, it's fixed now. Removing stale label, leaving issue clased.
