### ISSUE TITLE
Support for mPDF 7.x

### ISSUE THREAD

**Issue by KacerCZ** [PHPOffice/PhpSpreadsheet#144]
Hi,
fix of issue https://github.com/PHPOffice/PhpSpreadsheet/issues/37 used class `\Mpdf\Mpdf`.
Later pull request https://github.com/PHPOffice/PhpSpreadsheet/pull/76 changed used class to `\Mpdf`.

mPDF up to version 6.1 uses class `\mPDF`. 
From version 7.0 was added namespace and main class was renamed to `\Mpdf\Mpdf`, see https://github.com/mpdf/mpdf/blob/development/CHANGELOG.md

Is would be great if both versions could be supported, because mPDF 6.1 will not get support for PHP 7.1.

**Comment by PowerKiKi** [comment]
Thank you for the clarification. Clearly going back to non-namespaced code was a mistake. It should not have been merged that way.

Support for mPDF 6 must be dropped in favor of mPDF 7. Because mPDF 7 support all the same PHP versions as us. And we really don't have the resource to support two different versions.

Would you be able to submit a PR for that ?

**Comment by PowerKiKi** [comment]
Thank you for the clarification. Clearly going back to non-namespaced code was a mistake. It should not have been merged that way.

Support for mPDF 6 must be dropped in favor of mPDF 7. Because mPDF 7 support all the same PHP versions as us. And we really don't have the resource to support two different versions.

Would you be able to submit a PR for that ?

**Comment by KacerCZ** [comment]
PR with fix is here - https://github.com/PHPOffice/PhpSpreadsheet/pull/149
