### ISSUE TITLE
Can't get difference between datetimes

### ISSUE THREAD

**Issue by wast** [PHPOffice/PhpSpreadsheet#1634]
This is (I am not sure, all of the below)

```
- [*] a bug report
- [*] a feature request
- [*] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
To calculate valid formula for date difference.

### What is the current behavior?
Calculation result is #VALUE!

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheet->getActiveSheet()->getStyle('A1')->getNumberFormat()->setFormatCode('dd.mm.yyyy hh:mm');
$spreadsheet->getActiveSheet()->setCellValue('A1', '24.6.2020 12:30');

$spreadsheet->getActiveSheet()->getStyle('A2')->getNumberFormat()->setFormatCode('dd.mm.yyyy hh:mm');
$spreadsheet->getActiveSheet()->setCellValue('A2', '24.6.2020 15:00');

$spreadsheet->getActiveSheet()->setCellValue('A3', '=(A2 - A1)*24');

$writer = new PhpSpreadsheet\Writer\Html($spreadsheet);
$output = $writer->generateHTMLHeader();
$output .= $writer->generateStyles(true);
$output .= $writer->generateSheetData();
$output .= $writer->generateHTMLFooter();
$doc = new DOMDocument();
@$doc->loadHTML($output);
echo $doc->saveHTML();

```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.12 and 1.14.1
PHP 7.2.10

The result is 
![image](https://user-images.githubusercontent.com/9076227/91840346-da2ad380-ec50-11ea-9344-86a62055d021.png)
Expected is
![image](https://user-images.githubusercontent.com/9076227/91840405-ec0c7680-ec50-11ea-8b63-b03321a0411e.png)

Here is also the [StackOverflow question](https://stackoverflow.com/questions/63673491/).

**Comment by MarkBaker** [comment]
You're setting the cell value as a string containing the value `'24.6.2020 12:30'`, so PHPSpreadsheet treats it as a string, and the format mask is being ignored for that reason. If the string is supposed to be a date, then you need to convert it to an Excel serialised date/timestamp first, because PHPSpreadsheet won't automatically do this for you.

The documentation explains how to [set a date/time value in a cell](https://phpspreadsheet.readthedocs.io/en/latest/topics/accessing-cells/#setting-a-date-andor-time-value-in-a-cell) by converting it to a serialised date/timestamp using the `PHPToExcel()` method of the Shared `Date` class.

so use:
```
$spreadsheet->getActiveSheet()->getStyle('A1')->getNumberFormat()->setFormatCode('dd.mm.yyyy hh:mm');
$spreadsheet->getActiveSheet()->setCellValue('A1', \PhpOffice\PhpSpreadsheet\Shared\Date::PHPToExcel('24.6.2020 12:30'));

$spreadsheet->getActiveSheet()->getStyle('A2')->getNumberFormat()->setFormatCode('dd.mm.yyyy hh:mm');
$spreadsheet->getActiveSheet()->setCellValue('A2', \PhpOffice\PhpSpreadsheet\Shared\Date::PHPToExcel('24.6.2020 15:00'));
```
