### ISSUE TITLE
Bug in function XmlScanner::toUtf8 -> Suspicious Double-encoded XML

### ISSUE THREAD

**Issue by JulienChavee** [PHPOffice/PhpSpreadsheet#1681]
This is:

```
- [ x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
A file encoded with something different than UTF-8 can be imported

### What is the current behavior?
When we have an XML file that has the "encoding=..." the function in XmlScanner::toUtf8 will always throw an exception.

The call the mb_convert_encoding() do not modify the XML to change the "encoding=...". 
As of this, when you check again if the charset is now UTF-8 the second time, it's still false as it's based on the preg_match.

### Which versions of PhpSpreadsheet and PHP are affected?
\>= 1.12

**Comment by JulienChavee** [comment]
This is still an issue.

**Comment by oleibman** [comment]
Adding in the necessary support would involve a lot of work, without a lot of gain. Your suggestion might work for certain character sets, but would require extra work for others (e.g. UTF-16). Even so, there would be other things we need to check for beyond the XML declaration (e.g. charset or content-type declaration) which would also have to be changed to make the document usable, and we would need to change them only when they are attributes rather than content, and even then only when they are attributes for the right tag (e.g. we want to find charset in a meta tag but not in a script tag). In addition, I don't think the Php DOM parser handles the HTML5-style meta charset (it does handle the old meta content-type). I don't think the UTF-8 restriction is an onerous requirement, so I cannot justify the effort that would be required to make this change; however, I will be glad to review a PR if you wish to submit one.

This restriction should be documented. I will open a PR that updates the documentation appropriately.
