### ISSUE TITLE
Update jquery to 3.5?

### ISSUE THREAD

**Issue by monelgordillo** [PHPOffice/PhpSpreadsheet#1711]
This is:

```
- [ ] a bug report
- [X ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Jquery 3.5, instead of 3.1

### What is the current behavior?
Jquery 3.1

![image](https://user-images.githubusercontent.com/36521543/99091553-abf13a80-2595-11eb-8653-ee0e35da31f5.png)
![image](https://user-images.githubusercontent.com/36521543/99091642-c4f9eb80-2595-11eb-9e20-4dccfd7a491a.png)

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

See image.

### Which versions of PhpSpreadsheet and PHP are affected?
Current version.

**Comment by waqleh** [comment]
another reason why this is a good idea: "In jQuery versions greater than or equal to 1.0.3 and before 3.5.0, passing HTML containing <option> elements from untrusted sources - even after sanitizing it - to one of jQuery's DOM manipulation methods (i.e. .html(), .append(), and others) may execute untrusted code. This problem is patched in jQuery 3.5.0."

https://cve.circl.lu/cve/CVE-2020-11023

**Comment by thinkspill** [comment]
This issue is causing security scanners to flag this library as vulnerable.

**Comment by waqleh** [comment]
@oleibman or @PowerKiKi can you add a new tag so I can deploy the fix in my project via composer

**Comment by oleibman** [comment]
Done today.
