### ISSUE TITLE
Where is the download?

### ISSUE THREAD

**Issue by accorinti** [PHPOffice/PhpSpreadsheet#1720]
When I download the zip file I only get the source code. Where is the download with samples and docs?
Thanks

**Comment by MarkBaker** [comment]
If you composer install it, then you'll get samples, docs, unit tests, etc.
The download zip is purely the code, because users have told us that is all they want in the zip

**Comment by accorinti** [comment]
Well I dont use the composer and I guess there are a lot of people also that like the manually way. 
In your examples you show how to start with
require vendor/autoload.php
but there is nothing in the download.
There is no arm in putting everything in the ZIP, so everyone gets what they want....

So, where can I download everything?

**Comment by MarkBaker** [comment]
`There is no arm in putting everything in the ZIP, so everyone gets what they want....`
You can't download everything in one package as a zip: as I said, a lot of users don't want everything in the zip download. I'd certainly recommend using composer, not simply for PHPSpreadsheet, but for most modern PHP libraries and frameworks, and also to handle the autoloading of files and classes.

If you absolutely must use the downloaded zip; then you'll have to download dependencies manually as well; and handle the autoloading yourself. The documentation for the library is available [online](https://phpspreadsheet.readthedocs.io/en/latest/), as is the [API documentation](https://phpoffice.github.io/PhpSpreadsheet/).

**Comment by accorinti** [comment]
Thank you for your answer. But look at the link you sent, the 
documentation shows how to do things that are not possible with the actual download.

![Clipboard01](https://user-images.githubusercontent.com/10834155/99885476-73a4c880-2c35-11eb-9ab1-455157a6575e.jpg)

**Comment by MarkBaker** [comment]
The instructions assume that you will use the recommended approach, and use composer to install PHPSpreadsheet. If you choose not to follow that recommendation, then you need to do a few things differently; and if you have made a conscious decision not to follow recommendations and use composer, then you should have the necessary knowledge to adapt code to use your own autoloading instead.


Step #1. Download the PHPSpreadsheet zip, and extract the contents to an appropriate folder
Step #2. Download all necessary dependencies (referenced in the composer.json file), and extract them to appropriate folders (you will also need to ensure that dependencies of those dependencies are also downloaded and extracted)
Step #3. Write (or adapt) your own autoloader to ensure that classes and files for PHPSpreadsheet and all its dependencies are loaded as required.
Step #4. When writing your code, include your own autoloader instead of the composer autoloader (`vendor/autoload.php`)

**Comment by accorinti** [comment]
Hello and thanks for your answer, I appreciate it.

But things does not have to be so complicated. I downloaded a Zip-File from this website, extract it and it works right out of the box: 
https://php-download.com/package/phpoffice/phpspreadsheet

Greets

**Comment by PowerKiKi** [comment]
Installs without composer is not supported.
