### ISSUE TITLE
[Feature] Not able to set escape character for Writer\Csv

### ISSUE THREAD

**Issue by joern19** [PHPOffice/PhpSpreadsheet#1798]
This is:

```
- [ ] a bug report
- [ x ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

I need to be able to set the escape character in "PhpOffice\PhpSpreadsheet\Writer\Csv.php".
Currently only the reader version ("PhpOffice\PhpSpreadsheet\Reader\Csv.php") supports to set the escape character.

### Which versions of PhpSpreadsheet and PHP are affected?
I am using 1.12.0 but I will update to the newest version asap. 
The feature still does not exist in the newest version (1.16.0)

**Comment by oleibman** [comment]
RFC 4180 (https://tools.ietf.org/html/rfc4180), which is effectively the
standard for CSV files, does not have the concept of an escape character.
It is unfortunate that PHP introduced the concept to fgetcsv and fputcsv functions,
doubly so because the semantics of the escape character are not adequately documented,
and certainly not intuitive (the following are representative of
many documented issues):
https://stackoverflow.com/questions/26840256/fgetcsv-fputcsv-escape-parameter-fundamentally-broken
https://stackoverflow.com/questions/57634338/fputcsv-fails-to-escape-entire-cells-containing-a-slashed-double-quote

PhpSpreadsheet does use fgetcsv for input, and thus supported the concept there.
This is, again, unfortunate, as extra application code is needed to correctly
read a valid CSV file which happens to include the escape character.
It does not use fputcsv for output, so does not support it there.
It would be a mistake to add such support. *You will produce files which cannot
be correctly read by Excel.*

Having said all that, why in particular do you feel that you require an
escape character for your output files? With that information, it might be
possible to suggest an alternative that meets your needs.

**Comment by joern19** [comment]
The Problem solved itself.
Closing the Issue.
