### ISSUE TITLE
Is it possible to get a tag ? 

### ISSUE THREAD

**Issue by romaricp** [PHPOffice/PhpSpreadsheet#183]
This is:
- [x] a feature request

### What is the expected behavior?
I would like to use this on my project Symfony but after test by insight.sensiolabs, fail.. Because we use : 
``` JSON
"phpoffice/phpspreadsheet": "dev-develop",
```

And it's a bad practice to use a dependency with "dev-develop".
So is it possible to get a v1 or v0.1 please ?

Best regards, 
Romaric.

**Comment by romaricp** [comment]
Modify title

**Comment by ladislavP** [comment]
Problem is also that instruction from documentation:

`composer require phpoffice/phpspreadsheet`

is not working in for me standard configuration: **minimum-stability: stable** because of composer error:

_Could not find package phpoffice/phpspreadsheet at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability_

**Comment by MikkelPaulson** [comment]
Indeed. At what point will PhpSpreadsheet be considered stable? Is there a roadmap for stable release?

**Comment by alavieille** [comment]
Even if the maintainer doesn't consider PhpSpreadsheet that stable. i can always create a beta or an alpha tag. i think it always better than use directly a branch.

**Comment by bs-thomas** [comment]
It would be really great to have at least a tag.  There are no releases nor tags currently, and it's somewhat hard to maintain the versioning.

Also, seems like that library works nicely so far, I wonder if there are any expected release dates or milestones for this.

Thanks!!

**Comment by exussum12** [comment]
+1 especially as the composer dependencies change

**Comment by mbarrus73** [comment]
What is the workaround for this?

**Comment by PowerKiKi** [comment]
`composer require phpoffice/phpspreadsheet:dev-develop` as written [in the docs](http://phpspreadsheet.readthedocs.io/en/develop/#installation).

**Comment by bs-thomas** [comment]
@PowerKiKi But that does not guarantee the stability and the version we retrieve.  For example, if we do composer install now, and do it a month later, the copies could be completely different.  Need need time-based tags as the project development goes on.

**Comment by exussum12** [comment]
More annoyingly the depended version of php was bumped to 7 so breaks PHP 5 installs

**Comment by exussum12** [comment]
For example https://github.com/PHPOffice/PhpSpreadsheet/commit/682b1b8cb2bff29fdb2e72ae18512733e0be8b9e

Bumped the version so people on older version of php can't use it now   if there was a tagged version support would not be effected. I don't understand why you would not want to tag

**Comment by PowerKiKi** [comment]
@bs-thomas, yes it does. Composer guarantees you to always get the exact same install no matter how you require them, as long as you commit composer.lock. And [you should](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/).

@exussum12 this is wrong, PHP 5.6 is still supported by PhpSreadsheet, because [PHP 5.6 is the last 5.x version that is still officially supported by PHP core](http://php.net/supported-versions.php).

**Comment by PowerKiKi** [comment]
[PhpSpreadsheet 1.0.0-beta](https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/CHANGELOG.md#100-beta---2017-08-17) was just released

**Comment by bs-thomas** [comment]
Sweet.  Thank you so much @PowerKiKi

**Comment by romaricp** [comment]
\o/ \o/ \o/
Thanks !
