### ISSUE TITLE
getCell() no longer works with named cells

### ISSUE THREAD

**Issue by beard7** [PHPOffice/PhpSpreadsheet#1858]
This is:

```
- [ ] a bug report
- [*] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Accessing a named cell reference with `getCell('CELLNAME', false)` should return the cell object.

### What is the current behavior?
Throws an exception: Cell coordinate must not be absolute.

It's no longer possible to access a named cell using `getCell()`, which means it's no longer possible to use PhpSpreadsheet as a 'template processor'.

This worked on previous versions. Is there a workaround or could a `getNamedCell()` method be added?

### What are the steps to reproduce?
Use `getCell()` with a named cell.

### Which versions of PhpSpreadsheet and PHP are affected?
1.15.0

**Comment by MarkBaker** [comment]
The changes to named ranges in release 1.15.0 mean relative and absolute addresses in ranges are now handled correctly (as MS Excel handles them, rather than always treating them as absolute) in formulae (previously, this was not the case).

It seems that I overlooked the fact that `getCell()` also supports access to a named cell; and it wasn't simply Formulae that used them.

Expect a fix to master later today, and for the 1.17.0 release.

**Comment by beard7** [comment]
@MarkBaker brilliant.

Thanks for the quick fix!

**Comment by MarkBaker** [comment]
Resolved
