### ISSUE TITLE
Error when saving an Xlsx file (with images) with the same name!

### ISSUE THREAD

**Issue by DiogoMestre** [PHPOffice/PhpSpreadsheet#1911]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
An xlsx file with images can be saved several times with the same name, without errors occurring.

### What is the current behavior?
When we try to save a file with images, that already exists with the same name, an error occurs.
```
PHP Fatal error:  Uncaught PhpOffice\PhpSpreadsheet\Writer\Exception: File zip://C:\Users\diogo\Documents\PhpSpreadsheet\test.xlsx#xl/media/54b0c99f8d2c2a408c3a8abee180cd941.png does not exist in C:\Users\diogo\Documents\PhpSpreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\ContentTypes.php:198
Stack trace:
#0 C:\Users\diogo\Documents\PhpSpreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\ContentTypes.php(126): PhpOffice\PhpSpreadsheet\Writer\Xlsx\ContentTypes->getImageMimeType()
#1 C:\Users\diogo\Documents\PhpSpreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx.php(216): PhpOffice\PhpSpreadsheet\Writer\Xlsx\ContentTypes->writeContentTypes()
#2 C:\Users\diogo\Documents\PhpSpreadsheet\BugReport.php(30): PhpOffice\PhpSpreadsheet\Writer\Xlsx->save()
#3 {main}
  thrown in C:\Users\diogo\Documents\PhpSpreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\ContentTypes.php on line 198
```

### What are the steps to reproduce?
1) Create an Xlsx file with images.
2) Save this file.
3) Load the file;
4) Save it again with the same name.
 
Note: I'm using the same code used by @PowerKiKi  in this comment [https://github.com/PHPOffice/PhpSpreadsheet/issues/544#issuecomment-427643848](https://github.com/PHPOffice/PhpSpreadsheet/issues/544#issuecomment-427643848). The unique difference is that I'm saving the second Xlsx file with the same name as the first file.

```php
<?php
require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Worksheet\MemoryDrawing;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Create new Spreadsheet object
$spreadsheet = new Spreadsheet();

// Generate an image
$gdImage = imagecreatetruecolor(250, 30);
$textColor = imagecolorallocate($gdImage, 255, 255, 255);
imagestring($gdImage, 4, 5, 5, 'Created with PhpSpreadsheet', $textColor);

// Add a drawing to the worksheet
$drawing = new MemoryDrawing();
$drawing->setImageResource($gdImage);
$drawing->setWorksheet($spreadsheet->getActiveSheet());

$writer = new Xlsx($spreadsheet);
$writer->save('test.xlsx');

$reloaded = IOFactory::load('test.xlsx');

$reloaded->getActiveSheet()->setCellValue('D5', 'foo');

$writer = new Xlsx($reloaded);
$writer->save('test.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: v1.17.1
PHP: v7.4.13;

**Comment by ccrims0n** [comment]
This is specifically happening because of the way the xlsx file is opened before updating. It is opened in `ZipArchive::OVERWRITE` or `ZipArchive::CREATE` mode depending on if the file is existing or new. In your case, the XLSX file is opened using the `OVERWRITE` mode. According to the [PHP documentation](https://www.php.net/manual/en/zip.constants.php#ziparchive.constants.overwrite)
> ZipArchive::OVERWRITE (int) If archive exists, ignore its current contents. In other words, handle it the same way as an empty archive.

Although `PhpOffice\PhpSpreadsheet\Writer\Xlsx\ContentTypes::getImageMimeType()` tries to open the archive again under `ZipArchive::RDONLY` mode but the file is already open under the `OVERWRITE` mode, hence it fails and returns the error `File $pFile does not exist`.

Ideally, the excel file shouldn't be modified unless all the data is read completely in memory. However, the current code overrides files in an incremental fashion rather than doing it once.

The solution suggested by @luisfdgon would work for this since the file from where the data is read and written are different.

I will try to file a good solution to this to fix but doesn't look file it'd be easy without a refactor. If any of the core contributors can confirm if that's okay, I'd be happy to file a PR.

**Comment by ccrims0n** [comment]
This is specifically happening because of the way the xlsx file is opened before updating. It is opened in `wb+` mode.

Although `PhpOffice\PhpSpreadsheet\Writer\Xlsx\ContentTypes::getImageMimeType()` tries to open the archive under `ZipArchive::RDONLY` mode but it returns error 19 (`ZipArchive::ER_NOZIP`), hence it fails and returns the error `File $pFile does not exist`.

Ideally, the excel file shouldn't be modified unless all the data is read completely in memory. However, the current code overrides files in an incremental fashion rather than doing it once.

The solution suggested by @luisfdgon would work for this since the file from where the data is read and written are different.

I will try to file a good solution to this to fix but doesn't look file it'd be easy without a refactor. If any of the core contributors can confirm if that's okay, I'd be happy to file a PR.

**Comment by DiogoMestre** [comment]
The solution/workaround suggested by @luisfdgon works fine for me!  Thank you for that!

@ccrims0n, thank you for your detailed feedback about the problem and good luck with the work to find the best solution. I don't know if it is relevant or useful, but in PHPExcel this does not happen.

**Comment by ccrims0n** [comment]
> I don't know if it is relevant or useful, but in PHPExcel this does not happen.


> The solution/workaround suggested by @luisfdgon works fine for me! Thank you for that!
> 
> @ccrims0n, thank you for your detailed feedback about the problem and good luck with the work to find the best solution. I don't know if it is relevant or useful, but in PHPExcel this does not happen.

That's strange, given both PHPExcel and PHPSpreadsheet have almost common code for this. 
I'll debug more on this.

**Comment by MAKS-dev** [comment]
Perhaps he saves to xls with PHPExcel, which is a whole other file format (not a rar).

Anyway, may I be so bold to bump issue https://github.com/PHPOffice/PhpSpreadsheet/issues/1153 ? I'd really appreciate if someone would check that one as I'm hoping for a fix for so long (starting June 2018).
