### ISSUE TITLE
Official, Lightweight Docker Image

### ISSUE THREAD

**Issue by sammcj** [PHPOffice/PhpSpreadsheet#2]
It would be fantastic if there could be an official, lightweight (based off Alpine preferably) Docker image for PHPOffice and it's components (such as PHPSpreadsheet)

Lots of people are hesitant to install and maintain apps (Especially with PHP and I intend no offence) directly onto servers and having the ability to quickly spin up PHPOffice as a docker image on one or many servers not only greatly simplifies the install and deployment process, but can add a layer of security when coupled with SELinux and proper cgroup isolation. (Note: I am not saying that Docker itself adds security).

I found a popular PHP+FPM+Nginx base image that help you out: https://hub.docker.com/r/richarvey/nginx-php-fpm/ it should result in a nice lightweight image, ready to have the PHPOffice apps added on top which should be trivial for someone that knows the product set (not I).

**Comment by PowerKiKi** [comment]
I believe this is out of scope of this project, and would only add even more maintenance work for us that we could probably not assume well enough.

IMHO the usage of docker is also way overkill for a lib such as PhpSpreadsheet. This is a lib not a entire application. There is no real point of having this lib by itself, because it does not do anything by itself. You'll have to build, maintain, package and publish your own application anyway. So I think it's best that this responsibility stay with the application developers, not lib developers.
