### ISSUE TITLE
Cell coordinate can not be zero-length string

### ISSUE THREAD

**Issue by lawmillion** [PHPOffice/PhpSpreadsheet#201]
I'm import excel ,load file throw this error。
I don't know what to do

**Comment by lawmillion** [comment]
@GreatHumorist http://osia6vire.bkt.clouddn.com/test_excel.xlsx this is excel
`$this->reader = IOFactory::createReader('xlsx');
$this->reader->load($this->file);
`
PhpOffice\PhpSpreadsheet\Exception: Cell coordinate can not be zero-length string in /var/www/laravel/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell.php:603

**Comment by GreatHumorist** [comment]
Hi, I tried to resume this bug, and find out that it's the bug with xml.

As we know, a xlsx type file is a zip file in fact, so I decompressioned your xlsx file and another xlsx file which can be correctly read by phpspreadsheet,  I found that "./xl/worksheets/sheet1.xml" some difference:

-- Each xml node c in worksheet->sheetData->row is like '<c r="A1" s="3" t="s">' which is correct, but your xml is '<c s="47">', the attribute 'r' is the location of the data, 's' maybe is style, and 't' maybe is type, your node c in worksheet xml only include one attribute. When the phpspreadsheet reader read this xml file, it can't find a 'r' attribute so it reports a error message.

In order to solve this problem, you can try another software generate this file, or wait me to fix it. Maybe hours later.

**Comment by lawmillion** [comment]
@GreatHumorist  Hi,I found that can fix files with Excel software，but I hope to fix them with code。
Do not want to operate again，I hope you can fix it，thank you!

**Comment by GreatHumorist** [comment]
I have fixed this bug without strict test, you can update your code and try if it is correct.

If the code is correct  or not, pls tell me and give the sample data, I try to fix it again, or pull it.

**Comment by lawmillion** [comment]
@GreatHumorist Hi，Thank you，This code is work fine，I hope composer install you fix

**Comment by GreatHumorist** [comment]
Ok, I have pulled request, now is waiting merge. Could you pls give me a follow or star, thank you.

**Comment by lawmillion** [comment]
@GreatHumorist My pleasure.
