### ISSUE TITLE
Writing Excel XLSX with a sheet (tab) of derived values (formulae) is horrifically slow

### ISSUE THREAD

**Issue by chrisnoden** [PHPOffice/PhpSpreadsheet#2148]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behaviour?

When adding a sheet which is mostly lots of cells of formulae referencing other sheets to summarise data it is expected that Excel would calculate the values when the file is opened. Generating the additional sheet shouldn't take longer than it would take to write normal values (strings/ints/etc) to the cells.

### What is the current behaviour?

Writing a sheet of rows of values takes a few seconds to save. Writing a sheet of rows of formulae takes many, many minutes to hours to save.

### What are the steps to reproduce?

I'll try and create something

### Which versions of PhpSpreadsheet and PHP are affected?

Tested in 1.18.0 on PHP 8.0.7 but also seen in PHP 7.4 running v1.17.x

**Comment by MarkBaker** [comment]
This is behaviour that you can configure yourself: the Writer has a `setPreCalculateFormulas()` method; setting that to false will disable precalculation of formulae in the Writer, leaving it to the opening application (MS Excel) to handle formula calculation.

However, if you have set any columns to autosize, then PhpSpreadsheet needs to calculate formulae in the cells of that column in order to determine the size for the column, and this over-rides the `preCalculateFormulas` value for those cells.

**Comment by chrisnoden** [comment]
@MarkBaker 

> This is behaviour that you can configure yourself: the Writer has a `setPreCalculateFormulas()` method; setting that to false will disable precalculation of formulae in the Writer, leaving it to the opening application (MS Excel) to handle formula calculation.
> 
> However, if you have set any columns to autosize, then PhpSpreadsheet needs to calculate formulae in the cells of that column in order to determine the size for the column, and this over-rides the `preCalculateFormulas` value for those cells.

You are a star. Thank you.
