### ISSUE TITLE
Format xml relations ships

### ISSUE THREAD

**Issue by dansleboby** [PHPOffice/PhpSpreadsheet#2212]
https://github.com/PHPOffice/PhpSpreadsheet/blob/418cd304e8e6b417ea79c3b29126a25dc4b1170c/src/PhpSpreadsheet/Reader/Xlsx.php#L1949

Hi I have a document with this ref instand: http://purl.oclc.org/ooxml/officeDocument/relationships/officeDocument and it broke the script and I don't know why

https://github.com/PHPOffice/PhpSpreadsheet/issues/1718#issuecomment-826625060

Thanks

**Comment by dansleboby** [comment]
https://social.msdn.microsoft.com/Forums/en-US/050e791a-c59b-45b6-80b5-e5798ee47b7a/why-the-relationship-type-diff-between-ecma376-and-iso-29500?forum=os_binaryfile

**Comment by MarkBaker** [comment]
Were busy working on improving the namespace handling at the moment. Rather than checking the code for the 1.18.0 release, check the [master branch](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Reader/Xlsx.php#L1941) to see what changes have been made since then... and test your file against the master branch to see if it works, because we have precious few examples to test against

**Comment by dansleboby** [comment]
Yes working great from master, an ETA for stable release?

**Comment by MarkBaker** [comment]
This month.... but it' a fairly major internal change, and "high risk" so need  a lot more testing

**Comment by oleibman** [comment]
Closing. Fixed in release 19/20.
