### ISSUE TITLE
Applying Styles on Named Ranges fails

### ISSUE THREAD

**Issue by bjalt** [PHPOffice/PhpSpreadsheet#2279]
This is:

```
- [ ] a bug report
- [x] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The styles can be applied using named ranges.

### What is the current behavior?
Exception thrown in `/src/PhpSpreadsheet/Cell/Coordinate.php` on line 42 with message `Invalid cell coordinate`

### What are the steps to reproduce?

```php
<?php

require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Shared\Date;
use PhpOffice\PhpSpreadsheet\Spreadsheet;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', Date::stringToExcel((new DateTime())->format('Y-m-t')));
$spreadsheet->addNamedRange( new \PhpOffice\PhpSpreadsheet\NamedRange('EXAMPLE', $sheet, '=$A$1') );

$sheet->getStyle('EXAMPLE')->getNumberFormat()->setFormatCode('yyyy-mm-dd');
```

### Which versions of PhpSpreadsheet and PHP are affected?
I tried with 1.18 but I suspect that the change in 1.15 and the new possibilities with Named Ranges are the cause of the issue.

**Comment by oleibman** [comment]
The getStyle method does not support named ranges, and I don't think the 1.15 change affected that. You can certainly make a case that it should support them, or at least throw an exception if they remain unsupported. But there are complications; for example, what should happen if the named range is on a different sheet? Also, I don't think Excel offers an option to style a named range; you can effectively do that by selecting all the cells in the range and styling them, but you can equally well do that in your application (by specifying the actual coordinates rather than the defined name).

**Comment by bjalt** [comment]
@oleibman Thank you for your input. I've implemented the selection of all cells in the the range. Throwing an exception would a good addition.

**Comment by PowerKiKi** [comment]
Fixed in https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.19.0
