### ISSUE TITLE
Error with reading file

### ISSUE THREAD

**Issue by Glarionov** [PHPOffice/PhpSpreadsheet#2362]
This is:

```
- a bug report
```

### What is the expected behavior?
I want to read data from file by [this link](https://www.cbr.ru/Queries/UniDbQuery/DownloadExcel/123126?FromDate=10%2F27%2F2021&ToDate=10%2F27%2F2021&posted=False)

### What is the current behavior?
But PhpSpreadsheet can't read it.
It shows and error, if I try to read "first sheet" and if I want to count sheets, it shows zero.

### What are the steps to reproduce?

You need to download file by my link and save it as "RC_F27_10_2021_T27_10_2021.xlsx".

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$inputFileName = 'RC_F27_10_2021_T27_10_2021.xlsx';

$inputFileType = \PhpOffice\PhpSpreadsheet\IOFactory::identify($inputFileName);
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader($inputFileType);
$spreadsheet = $reader->load($inputFileName);
echo "Count: " . $spreadsheet->getSheetCount();
```

### Which versions of PhpSpreadsheet and PHP are affected?

I'm using current version of PhpSpreadsheet  and PHP 7.4

**Comment by oleibman** [comment]
Your problem is basically due to namespacing, however it has a new wrinkle. The first part of an effort to support namespacing has been pushed to master. However, your spreadsheet is still unreadable even in master because, when it attempts to open one of the files using ZipArchive::Open, it gets a return code of ZipArchive::ER_INCONS, indicating that the zip archive is "inconsistent", whatever that means. I am not sure how important the test for consistency is; this is the first file I've seen with such a problem. It will take a while to research.
