### ISSUE TITLE
Image missing

### ISSUE THREAD

**Issue by DeekshaPrabhub96** [PHPOffice/PhpSpreadsheet#2396]
This is: In one one of the scenario I observed the image is missing from a sheet. I have mentioned the steps to reproduce below.

### What is the expected behavior?
Image shouldn't be missing.

### What is the current behavior?
Image is getting removed.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:
Steps:
Create a Xlsx with 7 sheets. Add image to sheets 1,2,4,7.
Add a List Box from Developer tab to sheet 6
Add a button to Sheet 7 along with a image.

After opening and saving the file with different name using PHPSpreadsheet, I see the image is missing from sheet 4. I have attached a sample excel where issue can be easily reproduced.

```php
<?php
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();

// add code that show the issue here...

$spreadsheet = $reader->load($file);

$writer = new Xlsx($spreadsheet);
$writer->save('TextColorOutput.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.19
[ImageIssueInput.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7532647/ImageIssueInput.xlsx)

**Comment by oleibman** [comment]
Working in 17.1, not working in 18. Similar to  #2387 in that respect.

**Comment by oleibman** [comment]
I was hoping that some other work I was doing would help enlighten me about this. So far no dice. 2387 appears unrelated after all. This may be related to #1767, a problem I have not gained any traction on in some time.

**Comment by oleibman** [comment]
Both 17.1 and 18.0 are wrong. The problem lies deeper than the change between the two. The original spreadsheet has drawing files named drawing1/2/3/4/5.xml. Drawing 1 is associated with sheet 1, 2 with 2, drawing 3 with sheet 4, drawing 4 with sheet 6, and drawing 5 with sheet 7. The reader renumbers them to drawing 1/2/4/6/7. The drawing on sheet 6 is 'unparsed'. When the writer tries to add the unparsed data from sheet6, it does so using the original id drawing4.xml. This is in conflict with the renamed files. As luck would have it, 17.1 resolves the conflict by keeping the first drawing4.xml (which happens to result in a correct worksheet), and 18.0 resolves it by keeping the second one (which causes this problem). Something needs to be done with the reader and/or writer to avoid this name collision in the first place.

**Comment by oleibman** [comment]
Please test against 2423 if possible. It should fix the missing image problem. It doesn't do anything about ListBox or Button. My inclination would be to open a separate issue for those; I'm not sure whether they're supposed to be supported or not. I will probably leave this PR unmerged for a couple of weeks. The issue which I thought might be related does indeed seem to be at least partially fixed by this, and I want to allow for more testing there.

**Comment by oleibman** [comment]
Issue #1770 is probably relevant for ListBox and Button. Issue #1996 for Checkbox may also be relevant.

**Comment by DeekshaPrabhub96** [comment]
@oleibman  I commented some code from phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php, and that fixes the issue.

Commented from 430 to 438 in Writer/Xlsx.php(PhpSpreadsheet 1.19)
//             if (isset($unparsedLoadedData['sheets'][$sheetCodeName]['Drawings'])) {
//                 foreach ($unparsedLoadedData['sheets'][$sheetCodeName]['Drawings'] as $relId => $drawingXml) {
//                     $drawingFile = array_search($relId, $unparsedLoadedData['sheets'][$sheetCodeName]['drawingOriginalIds']);
//                     if ($drawingFile !== false) {
//                         $drawingFile = ltrim($drawingFile, '.');
//                         $zipContent['xl' . $drawingFile] = $drawingXml;
//                     }
//                 }
//             }


not sure if this will break any other things, could you please confirm if the changes makes sense?

**Comment by oleibman** [comment]
Have you tried testing against 2423? I think your proposal may cause lots of regression problems.

**Comment by PowerKiKi** [comment]
Fixed in https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.21.0
