### ISSUE TITLE
Fill Style no longer working

### ISSUE THREAD

**Issue by cwolcott** [PHPOffice/PhpSpreadsheet#2412]
This is:

```
- [X a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When creating a fill style it should color the 
```
    protected static $lowControls = [
        'fill' => [
            'fillType' => Fill::FILL_SOLID,
            'startColor' => ['argb' => 'fcdfdf']
        ]
    ];

    protected static $highControls = [
        'fill' => [
            'fillType' => Fill::FILL_SOLID,
            'startColor' => ['argb' => 'e0fde0']
        ]
    ];
```
```
        $worksheet->getStyle('G1:I2')->applyFromArray(self::$highControls);
```
![image](https://user-images.githubusercontent.com/3777526/143179171-fd2d835d-8ac0-4af3-9026-5b859e03caf3.png)

### What is the current behavior?
Cells are no longer being filled.

![image](https://user-images.githubusercontent.com/3777526/143179457-39e52451-037e-4132-b924-0e9ef6e5dcad.png)

### What are the steps to reproduce?
Define the above styles and apply them.

### Which versions of PhpSpreadsheet and PHP are affected?
1.18.0 - When everything was working
Upgrade to 1.20.0 and it did not work.

I will go back to 1.18.0 and then upgrade to 1.19.0 and finally to 1.20.0 to find where the issue was introduced.

**Comment by Rockylars** [comment]
You are using an RGB format with ARGB as the format set, either use FF in front of your current format or change your format to be RGB. This was also discussed in #2366.

**Comment by cwolcott** [comment]
Yep that fixed it, so sorry that I submitted this.  I looked the the release notes for 1.19.0 and 1.20.0 and missed it.

**Comment by villarruel** [comment]
After debugging the setARGB function I realized that the function expects a value in hexadecimal but in uppercase, if it sends the color in lowercase the function sets a default color because it falls into an error. Don't add FF before hex if you use setARGB, better use setRGB with only 6 digits for hex.
--------------------
Después de depurar la función setARGB me di cuenta que la función espera un valor en hexadecimal pero en mayúsculas, si  le envía el color en minúsculas la función establece un color predeterminado por que cae en un error. No agreguen FF antes del hexadecimal si usan setARGB, mejor usen setRGB con solo 6 dígitos para hexadecimal. 

Saludos.

**Comment by cwolcott** [comment]
Agreed using RGB, but I did use lowercase for the argb parameter and it worked fine.
```
    protected static $highControls = [
        'fill' => [
            'fillType' => Fill::FILL_SOLID,
            'startColor' => ['argb' => 'ffe0fde0'] 
        ]
    ];
```
