### ISSUE TITLE
Can't read Xls 97-2003 file generated from app

### ISSUE THREAD

**Issue by junaidimunto** [PHPOffice/PhpSpreadsheet#2490]
I can't read Xls 97-2003 formatted file generated from app (fingerprint machine). But when I manually create 97-2003 Xls or even newer version using Ms. Excell, my code run properly and successfully read the sheet. Is it problem with compatibility check?
For addition, the warning "Protected view" appears when I open this Xls 97-2003 file using Ms. Excel, and also "Excel 4 Worksheets" detected.
`$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($file->getTempName());`
`$reader->setReadDataOnly(true);`
`$spreadsheet = $reader->load($file->getTempName());`
`$sheet = $spreadsheet->getActiveSheet();`

[2022-01-01_04.xls](https://github.com/PHPOffice/PhpSpreadsheet/files/7834424/2022-01-01_04.xls)

**Comment by oleibman** [comment]
PhpSpreadsheet supports reading xls files in BIFF5 (introduced in 1993) or BIFF8 format. Your file uses BIFF4 format, which has been obsolete for almost 30 years. Excel still supports it, but, as you saw, there are, by default, restrictions on that format (probably due to concerns about macros). However, Excel does come with a command-line tool that will convert the file from xls to xlsx, and you could use that before processing your file - see http://justgeeks.blogspot.com/2014/08/free-convert-for-excel-files-xls-to-xlsx.html

**Comment by junaidimunto** [comment]
Wow, as mentioned in the article, I was also pleasantly surprised that Excel has command-line tool like that. I have just successfully executed the convertion in just a second even though it takes a little bit of time to find actual path of excelcnv file due to my newer office version. Sad to know that my machine is that old btw.
Thank you so much.

**Comment by oleibman** [comment]
Initial suggestion solved the issue. There was a minor lingering problem which is solved by 2499, which was just merged. So, closing this issue.
