### ISSUE TITLE
Custom Regex validation fails

### ISSUE THREAD

**Issue by marcomoscardini** [PHPOffice/PhpSpreadsheet#2658]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Open Excel/libreOffice and find in the validation box the correct formula `NOT(ISERROR(REGEX(B4;"^\w{1,5}$")))`

### What is the current behavior?
when I select a cell with a custom dataValidation I read `NOT(ISERROR(regex(B4;"^\w{1,5}$")))`, where `regex` is in lowercase apparently breaking things.

### What are the steps to reproduce?

```php        
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...

             $sheet = $spreadsheet->getActiveSheet();
             $cellId = 'B4';
             $colIdx = 'B';
             $cellRange = $cellId.':'.$colIdx. 5120;
             $pattern = '^\w{1,5}$';
 
             $validation = $sheet->getCell($cellId)->getDataValidation();
             $validation->setType(DataValidation::TYPE_CUSTOM);
             $validation->setErrorStyle(DataValidation::STYLE_INFORMATION);
             $validation->setAllowBlank(false);
             $validation->setShowInputMessage(true);
             $validation->setShowErrorMessage(true);
             $validation->setShowDropDown(false);
             $validation->setErrorTitle('Input error');
             $validation->setError('Value is not in list.');
             $validation->setPromptTitle('Pick from list');
             $validation->setPrompt('Please pick a value from the drop-down list.');
             $validation->setFormula1('NOT(ISERROR(REGEX('.$cellId.';"'.$pattern.'")))');
             $validation->setSqref($cellRange);

// save file...

```

### Which versions of PhpSpreadsheet and PHP are affected?
Version 1.22.0 on PHP 8.0

**Comment by MarkBaker** [comment]
That's probably because PhpSpreadsheet doesn't recognise REGEX() as a valid MS Excel function.

**Comment by marcomoscardini** [comment]
Good morning Mark,

would that be a feature/evol request?

where can I find a list of supported functions? is there an array/table our do you have specific factories?

**Comment by marcomoscardini** [comment]
OK, my mistake MATCH does not work with REGEX :-(

**Comment by MarkBaker** [comment]
The best place to check supported functions is the [online documentation](https://phpspreadsheet.readthedocs.io/en/latest/references/function-list-by-category/), when the supported function lists are built from the code itself with each release. The best place to check for the documentation about function usage is the [MS online Documentation](https://support.microsoft.com/en-us/office/excel-functions-by-category-5f91f4e9-7b42-46d2-9bd1-63f26a86c0eb), because we try to adhere as closely as possible to the MS Excel behaviour. This isn't perfect, e.g. in MS Excel `=1+"$4.00"` returns `5` because "$4.00"` is treated as though it is 4.0 with a monetary format mask, but in PhpSpreadsheet it returns `1`... I'm working on improving those edge cases, but it's slow work. It doesn't help that Excel behaviour "evolves", and changes aren't always documented.

`REGEX()` is a LibreOffice function, but it isn't recognised by MS Excel; and while using regexp is available through VBA, we don't support VBA.

**Comment by marcomoscardini** [comment]
MS Excel does not support REGEX, really ? I am surprised! 
Do you know if there is an alternative to be used with "validations" ou "conditional formatting" ? Something able to parse Regular expressions.
 
I thank you anyway for all the work done so far.

**Comment by marcomoscardini** [comment]
Ok, all alternatives pass by VB... sooooo sad there is nothing that can be done. I hit a dead end.

Thank you again Mark for all your help and your compete answers. 

I will close the issue ;-(

**Comment by marcomoscardini** [comment]
Would it be possible to open an Excel Template containing VB script required to accomplish regex in formulas and insert the cells I need and save it all together in a xlsx? (workaround missing VB support)
