### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by lcsqlpete** [PHPOffice/PhpSpreadsheet#2660]
Is this library compatible with PHP 8.1?

**Comment by oleibman** [comment]
Yes. All changes must pass the entire unit test suite for all of 7.3/7.4/8.0/8.1.

**Comment by lcsqlpete** [comment]
Thanks.

**Comment by MarkBaker** [comment]
The [main page here on github](https://github.com/PHPOffice/PhpSpreadsheet) shows information about the last merge to master branch, that will become part of the next release.
![image](https://user-images.githubusercontent.com/770298/157324265-21d481c8-16c5-4c8f-a97b-52ddce81bbe1.png)
Clicking on the green tick symbol will let you see the results of the test suite across all supported versions of PHP (from 7.3 to 8.1), as well as version checks, style checks, phpstan and all elements of the CI Pipeline.

As we approach the end of Q2, we will also add the nightly PHP build into that matrix of PHP versions (initially with an allow fail option) which will allow us to check that we are fully compatible with the forthcoming PHP 8.2 release, and identify any potential problems and take whatever steps are necessary so that we will fully support 8.2 from the day of its release.

**Comment by vojtasvoboda** [comment]
When selecting the latest tag [https://github.com/PHPOffice/PhpSpreadsheet/tree/1.22.0](1.22.0) it shows me the red cross. Does this mean some problem with the latest version regarding PHP 8.0/8.1?

**Comment by MarkBaker** [comment]
Not necessarily.... the red cross indicates an issue with some task in the CI Pipeline; if you're really concerned, then you need to click on that red cross to drill down and find out the details.

It could be as bad as tests failing for a specific version of PHP (not necessarily 8.0 or 8.1)... that should never happen, because unit tests should always be passing before we do a merge to the master branch.
This was the case for the 1.22.0 release, where there were float precision failures against PHP 7.4 (failures for unit tests against one version of PHP will cancel the running of unit tests against other versions of PHP).
There have been a few instances recently where tests that passing in one CI run fail in another due to float precision settings changing in the PHP image that the tests run against.; and is a source of annoyance for us (e.g. `Failed asserting that 2.6532998322843198 is identical to 2.653299832284`) normally the image precision is set to 12 decimals, and that's what the tests run against; but if the image is set to use 14 decimals, then the test may fail. We've been updating some of our tests to run with that greater precision so that this won't occur in the future, but that takes time and effort, so it's a slow task.

The red cross was for a CI pipeline run for the 1.22.0 release was for an [update to the Change Log](https://github.com/PHPOffice/PhpSpreadsheet/commit/3c0004760d59d417a7d51c0d04105d772949c3ea); which shouldn't ever cause test to start failing. If you check the failure, then they are all precision errors as I've described above. If you then check back through the commit log, you can see the last actual code merge (which was actually a PHP 8.1 compatibility change) resulted n a green tick.



Alternatively, it could be a style or phpstan issue; again, these should always be passing before we do a merge. These failures shouldn't create any issues in using the library.

The most likely cause for a red cross is a scrutinizer fail; and that can be because a method has been modified that increases its complexity; or the unit tests coverage has decreased; or (most commonly) that scrutinizer has simply cancelled its run or timed out. These failures shouldn't create any issues in using the library.
