### ISSUE TITLE
Reader: Cannot read sheets containing formulas with INDIRECT method referencing different sheet

### ISSUE THREAD

**Issue by mjan4175** [PHPOffice/PhpSpreadsheet#2741]
This is:

```
- [x] a bug report
```

### What is the expected behavior?
Xlsx reader correctly loads the attached file.

### What is the current behavior?
Xlsx reader throws TestTarget!C1 -> Formula Error: An unexpected error occurred

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$xlsxFilename = '/path/to/attached/indirect.xlsx';

// this throws error
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($xlsxFilename);
$spreadsheet = $reader->load($xlsxFilename);
```

[indirect.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8462897/indirect.xlsx)

### Which versions of PhpSpreadsheet and PHP are affected?
tested on PHP 7.4, PhpSpreadsheet 1.22.0

**Comment by MarkBaker** [comment]
None of the Readers does anything to calculate data in the spreadsheet: calculation can only be executed when requesting data from a cell using `getCalculatedValue()`, `getFormattedValue()` or methods such as `toArray()`, or when saving the spreadsheet. And the Reader does correctly load the file as expected, and does not throw any exception.

When I run code that loads the file and then executes calculation of the formula using `getCalculatedValue()` against version 1.22.0, then I can confirm that it results in the error that you indicate. This issue with `INDIRECT()` has already been fixed in the `master` branch with [PR #2687](https://github.com/PHPOffice/PhpSpreadsheet/pull/2687)

**Comment by mjan4175** [comment]
Thanks for information and sorry for misleading bug report.

The exception was raised by Writer when saving file. I somehow mixed it up with another problem in my project.

mj.

**Comment by MarkBaker** [comment]
And hopefully, using `master` branch will resolve the calculation error: I expect to release a new version sometime in the next week, and certainly before the end of April.

**Comment by mjan4175** [comment]
I confirm, that `master` branch is OK. Looking forward to the release.
