### ISSUE TITLE
One more merged cells bug

### ISSUE THREAD

**Issue by alpha-and-omega** [PHPOffice/PhpSpreadsheet#289]
This is:

- [x] a bug report

### What is the expected behavior?
Xls reader should detect all merged cells

### What is the current behavior?
Xls reader does net detect some of the merged cells (partialy detected, partially not) in many user-provided documents (I have no idea how they were generated).

### What are the steps to reproduce?
I do not know how to generate these xls's documents from scratch, but  I have them on my production server, I can send the original document with this bug to developer.
I tried to fix it by myself without success.

Code to list merged cells:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$file = $argv[1];

$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xls');
$spreadsheet = $reader->load($file);
foreach ($spreadsheet->getWorksheetIterator() as $worksheet) {
	foreach ($worksheet->getMergeCells() as $cells) {
		var_dump($cells);
	}
}
?>

```

### Which versions of PhpSpreadsheet and PHP are affected?
All versions including develop branch.

**Comment by PowerKiKi** [comment]
What happen if you open the file with Excel 2016, save it as XLS and open that file instead of the original ?

**Comment by alpha-and-omega** [comment]
@PowerKiKi I did that in Libreoffice, after that Phpspreadsheet started to detect those mysterious cells.

**Comment by alpha-and-omega** [comment]
I tried to debug it, and I think there is unimplemented or undocumented biff8 merged-cells code in Phpspreadsheet, because these cells are not listed using this biff:
const XLS_TYPE_MERGEDCELLS = 0x00e5;
But I can be mistaken.
How can I privately send you this .xls ?

**Comment by PowerKiKi** [comment]
I unfortunately won't be able to debug this myself. If LibreOffice is able to "fix" the file, we may assume that the file was incorrect in the first place. But if you are able to debug it further and suggest a patch, I'll consider it for merging.

**Comment by alpha-and-omega** [comment]
The assumption can be incorrect. If anybody want's to hunt it - send me a message.

**Comment by CarlosNegrao** [comment]
I've ran into this problem recently, and since I couldn't find any other solution to the problem, I went to check the source code.

I found this part of  Xlsx.php where mergeCells is loaded: `
                            if ($xmlSheet && $xmlSheet->mergeCells && $xmlSheet->mergeCells->mergeCell && !$this->readDataOnly) {                              
                                foreach ($xmlSheet->mergeCells->mergeCell as $mergeCell) {
                                    $mergeRef = (string) $mergeCell['ref'];
                                    if (strpos($mergeRef, ':') !== false) {
                                        $docSheet->mergeCells((string) $mergeCell['ref']);
                                    }
                                }`

and by removing this part of the test: ` && !$this->readDataOnly` 

I could get the list of merged cells with getMergeCells(), which should be enough for me, since all I need is to read some files i have no control over.

I didn't familiarize myself enough with the code to understand the why of that test, let alone to figure out a proper workaround to submit, so I hope either someone who knows what they're doing can use this as a hint to properly solve the problem, or at least that other people with the same problem can benefit from this.
