### ISSUE TITLE
validate cannot be clear

### ISSUE THREAD

**Issue by season886** [PHPOffice/PhpSpreadsheet#2924]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

clear or delete Specify line number validate when set whole column validate

### What is the current behavior?

when set whole column validate cannot be clear the validate in cell

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
$date = ['one','two'];
$validate = $sheet->getDataValidation("A:A");
$validate->setType(DataValidation::TYPE_LIST)
            ->setErrorStyle(DataValidation::STYLE_STOP)
            ->setAllowBlank(false)
            ->setShowDropDown(true)
            ->setShowErrorMessage(true)
            ->setErrorTitle("Invalid value")
            ->setError("Invalid value");
$validate->setFormula1(sprintf('"%s"', implode(',', $data)));

$sheet->getCell('A1')->hasDataValidation() = false // is true?

$sheet->getCell('A1')->getDataValidation()->setType(DataValidation::TYPE_NONE)  //no effect;
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [x] Data Validations
- [ ] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by MarkBaker** [comment]
Well it can be cleared, because you can access the set of data validations, identify the column one that matches and rewrite it as a cell range rather than as column range; but I'll look at how to improve this so that the cell methods work more harmoniously with the worksheet methods for row and column ranges.

**Comment by MarkBaker** [comment]
Not so straightforward: if there's a dataValidation for `A:A`, and you create a new dataValidation for `A1`, then the `A:A` data validation still exists and will still be applied... so removing validation for cell `A1` means changing the existing dataValidation for `A:A` to `A2:A1048576`; more complicated if you wanted to remove validation for cell `A3`, because then `A:A` would need to be split into two data validation ranges for `A1:A2` and `A4:A1048576`.

**Comment by season886** [comment]
My purpose is to output the template file and define the validation, so that users can also use the validation column for insert new data, but the title not need validate.
The way I can think of is like this. Do you have any good ideas?

**Comment by season886** [comment]
```
 $excel = Excel::createSheet()->setValidate(['one','two'],1,2,'A','A');
 $excel->setValidate(['one','two'],4,1048576,'A','A')->export('xxx.xlsx');
```
it's works,thinks!

**Comment by MarkBaker** [comment]
There are no guarantees; and it may even depend on the order of the validations in the file when there's an overlap.

I also need to make some changes to Writers, because not all formats support row/column ranges for data validations, only cell ranges
