### ISSUE TITLE
Encoding issue with Html reader after upgrading to 1.24.0

### ISSUE THREAD

**Issue by tipo94** [PHPOffice/PhpSpreadsheet#2942]
This is:

- [X] a bug report
- [ ] a feature request

### What is the expected behavior?
Correct encoding of characters

### What is the current behavior?
Accented characters do not display correctly

### What are the steps to reproduce?
Create a sheet from html reader with accented characters

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Html();
$htmlString = "<table><tbody><tr><td>éàâèî</td></tr></tbody></table>";
$mySpreadsheet = $reader->loadFromString($htmlString);

$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($mySpreadsheet);
$writer->save('output.xlsx');

```

### What features do you think are causing the issue

- [ ] Reader
- [X] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
I didn't. test with other formats

### Which versions of PhpSpreadsheet and PHP are affected?
Only happens with phpspreadsheet 1.24.0, reverting to 1.23.0 fix the issue
Attached is the generated file for the example
[output.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/9122670/output.xlsx)
(EDIT, attached the wrong file)

**Comment by oleibman** [comment]
Possibly due to #2894 (PHP8.2 will deprecate a function that was being used without an entirely clear path away from it). I will investigate.

**Comment by oleibman** [comment]
Yes, that's it alright. PHP8.2 deprecates mb_convert_encoding from translating to HTML_ENTITIES because "PHP already provides built-in functions that support encoding/decoding ... HTML Entities." Yeah, right. The function they suggest is not a complete equivalent; another possibility which they suggest is "not recommended". The problem is that the DOM loadHtml function assumes ISO-8859-1, and you cannot override it with code - only by adding a character set tag in the data. Wow, just wow.

I should have a PR ready today or tomorrow. In the meantime, as a workaround you can always add to the start of your string:
```
<?xml encoding = "UTF-8">
```

**Comment by NomisGnos** [comment]
I tried the <?xml encoding = "UTF-8"> and it did not work for me.

**Comment by oleibman** [comment]
Strange, it certainly works for me. Sorry it doesn't for you. Fix is on its way.
```php
$htmlString =
    '<?xml encoding = "UTF-8">' . 
    '<table><tbody><tr><td>éàâèî</td></tr></tbody></table>';
```
