### ISSUE TITLE
Error save pdf (mpdf) when css > 1000 line

### ISSUE THREAD

**Issue by dovantien2911** [PHPOffice/PhpSpreadsheet#3098]
This is:

```
- [x] a bug report
```

### What is the expected behavior?
File: vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Html.php; function generateStyles()
function generateStyles return CSS in one line ( remove  join PHP_EOL );

### What is the current behavior?
File: vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Pdf\Mpdf.php; function save()
generate HTML with CSS in many line. 
array_chunk html 1000 line 
write each array lines to HTML
=> Error when css > 1000 line; lines[0] have tag "< style >" and lines[1] have close tag "< /style >"

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by oleibman** [comment]
What release of PhpSpreadsheet are you using? This was fixed by PR #2434 which was merged to master on Dec. 7, 2021, and would have been part of the 1.21.0 release. Sample samples/Pdf/21c_Pdf.php was designed to test it, and, even when I bump the number of spreadsheet rows in that sample from 500 to 1500, it still seems to work just fine. So, if you are at 1.21.0 or above and still have a problem, I will need to see your code to see if I can duplicate and fix your problem.

**Comment by dovantien2911** [comment]
Thank you @oleibman ,

I upgraded php8 and used PHPOffice/PhpSpreadsheet version 1.25. It works perfectly.

Please close this issue.
