### ISSUE TITLE
Is it possible to provide a version without using Composer?

### ISSUE THREAD

**Issue by jiataifeng** [PHPOffice/PhpSpreadsheet#3221]
Tried Composer, it changed system settings  and found lots of issues with php.ini. saying modules not found in ext folder but I visually found them. 
Do not have enough time to fixing Composer issue. 
why don't PhpSpreadsheet consider a version without  Composer?

**Comment by MarkBaker** [comment]
Composer is a dependency manager, responsible for identifying that you have a PHP configuration that can run PhpSpreadsheet, for installing the library and all of its dependencies, and for providing the autoloader.

It is used by most modern PHP libraries and frameworks, so I would strongly recommend learning how it works, what it actually does, and using it.

Composer should not ever change system settings; but it can change the dependencies in your `/vendor` folder.

Just because a module exists in the ext folder, that doesn't mean it's enabled in PHP. Composer tells you what required extensions are not enabled, not what can be enabled.


> Do not have enough time to fixing Composer issue.
> why don't PhpSpreadsheet consider a version without Composer?

You may not have the time to fix composer issues; but you expect us to spend our time preparing a fully downloadable version of PhpSpreadsheet... so you're telling us that your time is more valuable than ours.

**Comment by geraldholdsworth** [comment]
> Tried Composer, it changed system settings and found lots of issues with php.ini. saying modules not found in ext folder but I visually found them.
> Do not have enough time to fixing Composer issue.
> why don't PhpSpreadsheet consider a version without Composer?

Why not, instead of PhpSpreadsheet, download and use PHPExcel (it's predecessor)?

It still works, and there are even some forks where it has been made PHP8 compatible. You can download it to develop your website, and then upload the whole thing to the webserver (where, like me, you may not have access to run/install composer and then PhpSpreadsheet).

**Comment by MarkBaker** [comment]
> It still works, and there are even some forks where it has been made PHP8 compatible. You can download it to develop your website, and then upload the whole thing to the webserver (where, like me, you may not have access to run/install composer and then PhpSpreadsheet).

Unless you develop directly on the server where you run your production code, why don't you have access to run/install composer? That's something I simply cannot understand. You don't need composer on your production servers, only on the box where you do your actual coding and development work.
