### ISSUE TITLE
How to save 100k data into excel using this library?

### ISSUE THREAD

**Issue by Utsaww** [PHPOffice/PhpSpreadsheet#3237]
I am trying to import huge data using this PHPSpreadsheet library but it is taking more than 40mins to do so and failing most of the time, tried many cache solutions but nothing is more efficient, is there any solution for fast writing into a sheet or any suitable library to do this quickly 

1. In the documentation only share about cache no Implementation, so How will I implement caching?
2. Many people talk about downloading data in chunks what does it mean in terms of downloading data in an excel sheet using
PHPSpreadhseet?
3. Also I am having an issue while downloading Excel, not able to download excel sheets using this library!

folder structure - 
-------------------------------------------------------------------
index.php (file which is generating excel sheet)                        |
phpoffice-->phpspreadsheet->all library  files                         | 
--------------------------------------------------------------------
below is reproduced code - 

    ini_set('display_errors', '1');
    ini_set('display_startup_errors', '1');
    error_reporting(E_ALL);
    mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
    
    ini_set('memory_limit', '8000M');
    ini_set('max_execution_time', 0);
    
    require_once 'vendor/autoload.php';
    
    use PhpOffice\PhpSpreadsheet\Spreadsheet;
    use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
    
    // Create a new PHPExcel object
    $spreadsheet  = new Spreadsheet();
    $objPHPExcel = $spreadsheet -> getActiveSheet();
    // Create the first sheet,
    $objPHPExcel->setActiveSheetIndex(0);
    
    $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(38);
    $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(33);
    $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(33);
    
    $sheet->setCellValue('A1', 'Date');
    $sheet->setCellValue('B1', 'Processed Date Time');
    $sheet->setCellValue('C1', 'Articleid');
    
    $collection = (new MongoDB\Client("mongodb://)
    
    $docs = $collection->aggregate($aggregate);
    
    foreach ($docs as $results => $result) {
        $sheet->setCellValue('A' . ($results + 2), formatDateForEmail($result['pubdate']));
        $sheet->setCellValue('B' . ($results + 2), $result['captureddatetime']);
        $sheet->setCellValue('C' . ($results + 2), $result['articleid']);
    }
    
    ob_end_clean();
    
    $filename = md5(uniqid(rand(), true));
    $filename .= ".xls";
    
    try {
        $writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($objPHPExcel, 'Xls');
        $writer->save($filePath);
        } catch(Exception $e) {
            exit($e->getMessage());
        }
    
        // redirect output to client browser
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename="'.$filename.'"');
        header('Cache-Control: max-age=0');
    
        $writer->save('php://output');
    exit;

**Comment by MarkBaker** [comment]
That depends on exactly what you want to do, and what filetypes you're loading, what they contain: but caching is for saving memory usage, and always comes with an overhead in speed. And it's very difficult to give any more specific advice without knowing more detail.

If you're only interested in raw data from the file you're loading, then set data only; if you're reading csv files, then use PHP's native csv functions; or you could try reading in chunks, rather than loading the whole file in one go.

**Comment by Utsaww** [comment]
@MarkBaker I have updated my code and also mentioned difficulties.

**Comment by MarkBaker** [comment]
Ok, so you're not loading a file, you're creating and saving a file.
First point to note: Xls files have a limit of 65536 rows per worksheet, so if you have more than that many rows then you need to use Xlsx instead, which has a limit of 1,048,576 rows.
Second point to note: `$docs = $collection->aggregate($aggregate);` creates an in memory array from MongoDB, that's going to be using a large amount of your PHP memory before you even start populating your spreadsheet. I'm not familiar with MongoDB; but is there any method that will return the aggregate as an iterator rather than as an array?

You're using a `for` loop to populate the worksheet, setting each cell individually within each row; using `fromArray()` may be faster in that loop.

Your code is confusing spreadsheets with worksheets. An Excel file is a spreadsheet file that contains one or more worksheets
```
$spreadsheet  = new Spreadsheet(); // Creates a Spreadsheet containing a single worksheet
$objPHPExcel = $spreadsheet -> getActiveSheet(); // $objPHPExcel is now the Worksheet
// Create the first sheet,
$objPHPExcel->setActiveSheetIndex(0); // You're using Spreadsheet methods on the Worksheet object! 

$sheet->setCellValue('A1', 'Date'); // $sheet is never defined anywhere in your code
```

In answer to your specific questions:
> In the documentation only share about cache no Implementation, so How will I implement caching?
>
We provide a single "in memory" cache as standard, and that's used by default. We don't provide implementations of other caches, because those libraries already exist elsewhere . Choose and install a cache that implements [PSR-16 standard](https://www.php-fig.org/psr/psr-16/) such as [one of those listed here](https://packagist.org/providers/psr/cache-implementation), and tell PHPSpreadsheet to use that caching implementation before you instantiate your spreadsheet [as described here](https://phpspreadsheet.readthedocs.io/en/latest/topics/memory_saving/), and it will use that cache.

> Many people talk about downloading data in chunks what does it mean in terms of downloading data in an excel sheet using PHPSpreadhseet?
>
Chunking is for reading a file, not writing a file, so it's not aplicable.

> Also I am having an issue while downloading Excel, not able to download excel sheets using this library!
>
In what sense? An Excel file is a spreadsheet file containing one or more worksheets; but I see that you're trying to use Worksheet methods on the Spreadsheet object. Aside from that, what issues are you having?
