### ISSUE TITLE
ZipStream v3 Beta

### ISSUE THREAD

**Issue by maennchen** [PHPOffice/PhpSpreadsheet#3246]
This is:

- [ ] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
- [x] a request for feedback

Hi All :wave: 

Since this package is one of the main dependents on `maennchen/zipstream-php` and we just released a beta of v3, I would like to ask you for some feedback before we deploy the version as stable.

Since v3 will only support PHP 8.1 and up, you will probably want to wait until PHP 8.0 is no longer supported to use it.

* Discussion for feedback: https://github.com/maennchen/ZipStream-PHP/discussions/237
* Upgrade instructions: https://github.com/maennchen/ZipStream-PHP/tree/3.0.0-beta.2#upgrade-to-version-300

This release mainly focuses on internal code quality, which should make it easier for outside people to contribute to the project. The code (and the underlying standard) was quite cryptic until now which prevented most people from doing so.

Thanks!

**Comment by oleibman** [comment]
The 64-bit requirement might be a showstopper. We do not formally test 32-bit, but we also don't forbid it. I do run 32-bit tests from time to time just to make sure it works.

We still support Php7.4, so are locked at version 2.2.6. My first step then was to take a look at 2.3.0, which is Php8.0+. It seems to work okay with Php8.0. There were some errors with Php8.1/8.2. The problems in those tests are already fixed in master, but not in the latest release code that I was using to test. Ironically, they were fixed as a result of errors discovered testing 32-bit, and had not previously shown themselves in 64-bit tests. At any rate, that version looks okay.

Testing your Beta version, I received 272 errors. Most, if not all, of these are "Zipstream\Option\Archive not found". Based on your release notes, this is expected. It may require a change to only one statement, or, at least, a small number of statements. I will report back when I have had a chance to analyze and adapt the code.

**Comment by maennchen** [comment]
@oleibman Thanks for having a first look.

Requiring 64-bit was a conscious decision to make the library easier to understand. Do you know of any statistics how much 32-bit is still used?

If you find any errors in the v2 version, please let me know so that we can address those. :)

**Comment by oleibman** [comment]
No idea about 32-bit statistics.

For your beta version, I needed to make changes in 2 places (Ods writer as well as Xlsx). It wasn't obvious from the documentation, but I did explicitly need to specify sendHttpHeaders as false. The unit test suite ran without error or failure, but Excel balks at something in the output files. Since its diagnostic messages are poor, it may take a while for me to figure out its complaint.

2.3.0 does not have that problem, nor any others that I can see.

**Comment by maennchen** [comment]
@oleibman Ah yes, the last version only sent the HTTP headers by default if the name was set. I'll mention that in the upgrade instructions.

Can you try setting `defaultEnableZeroHeader` to `false`? Maybe excel doesn't like that part.

**Comment by maennchen** [comment]
Upgrade instructions have been improved in https://github.com/maennchen/ZipStream-PHP/commit/815cf35e8f5285ee91ff97403953519903b3d6f4

**Comment by oleibman** [comment]
I'm not exactly sure what `defaultEnableZeroHeader` does (even reading your updated upgrade instructions), but I am pleased to report that setting it as you suggested eliminates Excel's objection.

I will probably close this ticket in a day or two, but please feel free to open new ones if you have new Beta/RC/prod versions to test. However, bear in mind that we just eliminated Php7.3 as a possible environment very recently, so we probably won't get to a Php8.1+ requirement for about 2 years.

**Comment by maennchen** [comment]
The zero header setting means that the size of the file is not known beforehand and therefore not set in the file header. This is very useful when streaming large files and you only want to read them once or the stream is not seekable.

**Comment by oleibman** [comment]
Closing - investigation is done for now. For documentation purposes, the following code is used with ZipStream V2 in Writer\Xlsx and Writer\Ods:
```php
        $options = new Archive();
        $options->setEnableZip64(false);
        $options->setOutputStream($this->fileHandle);

        return new ZipStream(null, $options);
```

ZipStream v3 requires that this change (note that this will be a compile error for Php7.4) to:
```php
        $zip = new ZipStream(
            enableZip64: false,
            outputStream: $this->fileHandle,
            sendHttpHeaders: false,
            defaultEnableZeroHeader: false,
        );

        return $zip;
```

**Comment by maennchen** [comment]
@oleibman FYI XDebug 3.2 also no longer supports 32bit. I think the time is ripe to drop support.

Unfortunately nobody seems to have statistics about usage of PHP in 32bit systems.

**Comment by oleibman** [comment]
Interesting information - thanks for passing it on.

**Comment by bugeaud** [comment]
FYI to date there are still RP and NAS running with 32bits PHPs like ARMv7

**Comment by oleibman** [comment]
Thank you for the information.
