### ISSUE TITLE
[BC Break] reading xlsx throws "The table range must be at least 1 column and 2 rows"

### ISSUE THREAD

**Issue by kbond** [PHPOffice/PhpSpreadsheet#3277]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Load an xlsx file (worked in 1.25.2).

```php
(new Xlsx())->load($filename)
```

### What is the current behavior?

In 1.26.0, [throws exception](https://github.com/PHPOffice/PhpSpreadsheet/blob/5b6ceea9705b068f993e268e4debc566c2637063/src/PhpSpreadsheet/Worksheet/Table.php#L302):

```
The table range must be at least 1 column and 2 rows
```

### What are the steps to reproduce?

#3278

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

XLSX for sure.

### Which versions of PhpSpreadsheet and PHP are affected?

1.26.0

**Comment by MarkBaker** [comment]
Can you possibly upload an example file that contains a table which doesn't meet this criteria? There was certainly at least on change to table dimensions between 1.25.2 and 1.26.0; but that should have allowed single-row single-column autofilters ([PR #3111](https://github.com/PHPOffice/PhpSpreadsheet/pull/3111)); but Table Range has been a minimum 2 rows and 1 column since it's introduction in 1.23.0. However, Prior to 1.26.0, Reading Tables was completely unsupported; and only a basic AutoFilter could be loaded.

**Comment by kbond** [comment]
Added a failing test in #3278.
