### ISSUE TITLE
PhpSpreadsheet 1.导出文件并设置密码失败 2.读取设置密码的文件失败

### ISSUE THREAD

**Issue by Time-travelers** [PHPOffice/PhpSpreadsheet#3393]
This is:

```
a bug report

```

### What is the expected behavior?
1.生成设置文档密码的excel
2.读取设置文档访问密码的excel

### What is the current behavior?

1.导出文件并设置密码失败
2.读取设置密码的文件失败
### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php

<?php
require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\IOFactory;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

// 在第一行第一列写入 "Hello World"
$sheet->setCellValue('A1', 'Hello World');

// 创建一个 Xlsx 写入器
$writer = new Xlsx($spreadsheet);

// 设置访问密码为 111
$spreadsheet->getSecurity()->setPassword('111');

// 设置保护工作表
$spreadsheet->getActiveSheet()->getProtection()->setSheet(true);

// 保存到文件
$writer->save('hello.xlsx');



<?php
require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;

// 读取一个带有密码的 excel 文件
$spreadsheet = IOFactory::load('hello.xlsx');

// 设置访问密码
$spreadsheet->getSecurity()->setPassword('111');

// 获取活动工作表
$sheet = $spreadsheet->getActiveSheet();

// 读取第一行第一列的值
$cell = $sheet->getCell('A1')->getValue();

// 输出读取到的值
echo $cell;

```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ *] Reader
- [ *] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet  1.27
php 7.4

**Comment by oleibman** [comment]
There is no `setPassword` at the spreadsheet level. Instead of:
```php
$spreadsheet->getSecurity()->setPassword('111');
```
You could try some variation of:
```php
$spreadsheet
    ->getSecurity()
    ->setLockRevision(true)
    ->setLockStructure(true)
    ->setLockWindows(true)
    ->setWorkbookPassword('111');
```
This would lock the file for anyone looking at it in Excel; they would have to unprotect it (supplying the password) before they could edit. However, PhpSpreadsheet can still read the file without having to supply the password, so the setPassword statement could be eliminated from your second program.

It is possible that you want to require a password to view/read the file. This requires encryption, which PhpSpreadsheet does not support. This is in the documentation: 'If you need to completely prevent reading a file by any tool, including PhpSpreadsheet, then you are looking for "encryption", not "protection"'.

**Comment by oleibman** [comment]
Encryption support was added with PR #4975. Changing close status to "completed" from "not planned".
