### ISSUE TITLE
Custom format values for datetime containing milliseconds are not retrieved correctly.

### ISSUE THREAD

**Issue by h-tk** [PHPOffice/PhpSpreadsheet#3412]
This is:

- [x] a bug report

### What is the expected behavior?
The output up to version 1.27.1 is '2023/02/28 0:00:00.000'

### What is the current behavior?
Output is 'yyyy/mm/dd h:mm:ss.44985'

### What are the steps to reproduce?

```php
<?php
// set MS Excel custom format : yyyy/mm/dd h:mm:ss.000
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('custom_datetime_format.xlsx');
$worksheet = $spreadsheet->getActiveSheet();
$sheetData  = $worksheet->toArray(null, true, true, true);

// 1.27.1
// $sheetData[2]['A'] is '2023/02/28 0:00:00.000';

// 1.28.0
// $sheetData[2]['A'] is 'yyyy/mm/dd h:mm:ss.44985';
```

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

Caused by modifications to PhpOffice\PhpSpreadsheet\Style\NumberFormat\Formatter::toFormattedString in version 1.28.0.

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
xlsx tested

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.28.0
PHP8.0
[custom_datetime_format.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/10847384/custom_datetime_format.xlsx)

**Comment by MarkBaker** [comment]
Hmmm. Not so simple

I'd tightened up the regexp check for dates so that it wouldn't try to parse a currency with locale like `[$€-en_US]_(#,##0.00_);[$€-en_US] (#,##0.00)` as a date; but in doing so it seems I'm now interpreting `yyyy/mm/dd\ h:mm:ss.000` as a number (and there were no unit tests for a time with decimals).

Hopefully the new regexp that I'm testing now will identify this format mask as a date, without breaking the existing tests for currencies; and will still recognise duration formats

**Comment by oleibman** [comment]
Closing, apparently fixed 6 months ago.
