### ISSUE TITLE
suggest update maennchen/zipstream-php to => 3.0.0

### ISSUE THREAD

**Issue by itgenolife** [PHPOffice/PhpSpreadsheet#3430]
https://github.com/PHPOffice/PhpSpreadsheet/blob/0610e57c4880f33a740d388026191a451e1bba38/composer.json#L73

they have a newer version.

https://github.com/maennchen/ZipStream-PHP/releases

Maybe to 2.4.0, because is compatible with php 8.2

**Comment by oleibman** [comment]
PR #3410 addresses this. It is in draft status because (a) the code in Zipstream 3.0 cannot run on versions of Php which PhpSpreadsheet supports (7.4, 8.0, 8.1 32-bit, and 8.2 32-bit); and (b) I am not convinced there is yet a need to implement it (since 2.* will work fine with all releases of Php that we do support). If such a need does become established, I will move it forward.

**Comment by bobvandevijver** [comment]
I just got offered the upgrade for Zipstream 3.0 for my projects (by Renovate), but currently it is only blocked by PhpSpreadSheet. Would love to see support added (with #3410), although I agree that the main benefit would be running the latest version (there is possibly better some performance due to better optimization of the ZipStream project, but I haven't seen any numbers supporting that).

**Comment by oleibman** [comment]
That is useful information. It still sounds more like something you want rather than something you need, but I will leave this ticket open to assess how widespread situations like yours are.

**Comment by simPod** [comment]
Upgrade of psr/http-message to v2 is also blocked by Zipstream. We need to use Zipstream v3 in order to be allowed to install http-message v2.

**Comment by oleibman** [comment]
Thank you for the information. I have removed the draft status from the PR. I will probably wait till after the next official release to merge it.

**Comment by oleibman** [comment]
Closing. PR #3410 has been merged.
