### ISSUE TITLE
how to create text and images

### ISSUE THREAD

**Issue by fakol** [PHPOffice/PhpSpreadsheet#3440]
Where are at least some examples of the output of a picture with text how to combine it, I have some errors come out when I want to add a picture to one document

**Comment by MarkBaker** [comment]
You can find the documentation [here](https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#add-a-drawing-to-a-worksheet) and some examples [here](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/templates/sampleSpreadsheet.php#L261)

**Comment by fakol** [comment]
![image](https://user-images.githubusercontent.com/41354153/223522307-07de43c9-3cae-477a-8a59-fee448e35178.png)

**Comment by fakol** [comment]
You don't have any examples of pictures with text

**Comment by MarkBaker** [comment]
What do you mean "pictures with text"? The examples create a spreadsheet that contains both text and images.
What are you trying to do with pictures and text?

And please, if you post code, use copy/paste. I can't even run your code to see what is being created.

**Comment by fakol** [comment]
The problem is that he does not create a file, and I did not find examples with pictures and text that you did somewhere, I even just looked for them on the Internet, even they insert pictures there in a barbaric way because it's really difficult to find that not everyone will find it

**Comment by fakol** [comment]
It's just that I learned how to add text again using the Internet, and not your documentation, because in principle nothing is clear

**Comment by MarkBaker** [comment]
But looking at your code, you create a drawing object and attach it to a worksheet: you should probably be doing this inside your loop, because I'm guessing that each iteration should be a different image. But I can't see anywhere in your code where you're actually setting the image file for that drawing object, no call to set the image path.

I apologise if you think we're barbaric and unclear; but I have pointed you to the examples that we provide.

And it's not clear to me exactly what you are trying to do other than insert an image into a spreadsheet; the documentation and the examples tell you how to that.

**Comment by MarkBaker** [comment]
As for finding the documentation, I'm not sure how we can make it easier.

On the github page:
![image](https://user-images.githubusercontent.com/770298/223527825-2cd3b0d1-c48c-41b5-937e-99599c3dec24.png)

In the README file:
![image](https://user-images.githubusercontent.com/770298/223528307-708ae0ae-5a6b-4af6-895d-db1fa205c26a.png)

**Comment by fakol** [comment]
<?php
session_start();
require "../../vendor/config.php";
require "../../vendor/autoload.php";

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;



$table = mysqli_query($db, "SELECT * FROM `tovars`");

if(isset($_POST["export"])) {
    $items = array();
    /*while() {
        $items[$i] = array();
        $items[$i]["kod"] = $list["id"];
        $items[$i]["name"] = $list["tov_name"];
        $items = msort($items, "kod");
    }*/

    
    $spreadsheet = new Spreadsheet();
    $drawing = new Drawing();
    $sheet = $spreadsheet->getActiveSheet();
    $sheet->setTitle('Товары');
    $sheet->setCellValue('A1', 'что-то тестовое');
    
    $sheet->getStyle('A1')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
    $sheet->getStyle('A1')->getFill()->getStartColor()->setARGB('FFFF0000');
    $sheet->mergeCells('A1:H1');

    $sheet->getStyle('A1')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);

    $i = 2;
    while($list = mysqli_fetch_assoc($table)) {
        $sheet->setCellValue('A'.$i, $list["tov_name"]);
        $sheet->setCellValue('B'.$i, $list["tov_desc"]);
        $drawing->setName($list["tov_name"]);
        $drawing->setDescription($list["tov_desc"]);
        $drawing->setPath('/../uploads/'.$list["tov_img"]);
        $drawing->setHeight(36);
        $drawing->setCoordinates('C'.$i);
        $drawing->setOffsetX(10);
        $drawing->setWorksheet($spreadsheet->getActiveSheet());
        $sheet->getStyle('A'.$i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
        $sheet->getStyle('B'.$i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
        $i++;
    }

    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment;filename="01simple.xlsx"');
    header('Cache-Control: max-age=0');
    
    $writer = new Xlsx($spreadsheet);
    $writer->save('php://output');
}

**Comment by fakol** [comment]
![image](https://user-images.githubusercontent.com/41354153/223533246-66a65541-2529-4d91-a9f0-51bea7c7f0bf.png)

For some reason, he writes me this even though the directory and this image exist

**Comment by MarkBaker** [comment]
`/../uploads/'.$list["tov_img"]` would not be a valid directory path for an image file; the `/../` at the start of the path is telling PHP to look up a level from the root directory. That cannot exist, there is no directory level above root, so it will fail to find that path to the image.

And you still need to move `$drawing = new Drawing();` inside your loop; each image is a different image, so you need a separate drawing object for each.

**Comment by fakol** [comment]
![image](https://user-images.githubusercontent.com/41354153/223536096-9dcfe90a-2028-4820-a304-e078c25f7cb9.png)

file export.php
directory uploads in admin

**Comment by MarkBaker** [comment]
`/..` is saying go up one level from the **absolute root** of the filesystem (not possible, because you can't go up beyond the absolute root). You would probably be best using a relative path from your current working directory.

**Comment by fakol** [comment]
![image](https://user-images.githubusercontent.com/41354153/223539695-333eff48-edae-437d-9b3a-8293886cb145.png)

Well, to begin with, something turned out

**Comment by MarkBaker** [comment]
Have you moved `$drawing = new Drawing();` inside your loop yet? Otherwise you only have a single drawing object that you're trying to use for different images

**Comment by fakol** [comment]
I did this, another question is whether it is possible to create multiple sheets in one document if, yes, how

**Comment by MarkBaker** [comment]
Of course it's possible:

```php
$anotherWorksheet = $spreadsheet->createSheet();
$anotherWorksheet->setTitle('Second Worksheet');
```

**Comment by fakol** [comment]
![image](https://user-images.githubusercontent.com/41354153/223563381-1816532d-62ba-40d3-96ab-c10a41a1de4d.png)

Can you please tell me, but this is how you can combine the cells, I just can't find it again

**Comment by MarkBaker** [comment]
Perhaps you should start by understanding that images aren't inserted in a cell; they're overlayed above the grid of cells.

You probably don't want to merge the cells; but to set the row height so that it matches the size of the image (allowing for any margins)
[documentation](https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#setting-a-rows-height)

**Comment by fakol** [comment]
![image](https://user-images.githubusercontent.com/41354153/223666360-6a926bec-4a1d-4230-a242-41805a987344.png)

For some reason, it began to appear, although everything was fine yesterday

**Comment by MarkBaker** [comment]
Look at the directory path that's being shown, and fix that... `$list["tov_img"]` is an empty value: this is a basic PHP error.

**Comment by fakol** [comment]
As I understand it, it should activate the first sheet, but for some reason this does not happen
`$spreadsheet->setActiveSheetIndex(0);`
my code 

```
    $spreadsheet = new Spreadsheet();
    $spreadsheet->getProperties()->setCreator('Maarten Balliauw')
    ->setLastModifiedBy('Maarten Balliauw')
    ->setTitle('Office 2007 XLSX Test Document')
    ->setSubject('Office 2007 XLSX Test Document')
    ->setDescription('Test document for Office 2007 XLSX, generated using PHP classes.')
    ->setKeywords('office 2007 openxml php')
    ->setCategory('Test result file');
    $spreadsheet->setActiveSheetIndex(0);
    $sheet = $spreadsheet->getActiveSheet();
```

**Comment by fakol** [comment]
is it possible to somehow do the filling of the table like this?

![image](https://user-images.githubusercontent.com/41354153/223678077-061aa524-7960-4197-a709-0e6fe0ad6069.png)

**Comment by MarkBaker** [comment]
**MS Excel 101**

A Spreadsheet consists of 0, 1 or more Worksheets. If you have 1 or more Worksheets, then one (and only one) of those Worksheets can be "Active" (viewed or updated) at a time, but there will always be an "Active" Worksheet (unless you explicitly delete all of the Worksheets in the Spreadsheet).

When you create a new Spreadsheet in MS Excel, it creates the Spreadsheet with a single Worksheet ("Sheet1")
![image](https://user-images.githubusercontent.com/770298/223720048-ac111afd-8170-4153-af4d-c5703a7be1a2.png)
and that is the "Active" Worksheet.
![image](https://user-images.githubusercontent.com/770298/223726002-2c1f253f-e59a-49ab-9488-4e1bd8eca59b.png)
This is the same as 
```php
$spreadsheet = new Spreadsheet();
$activeWorksheet = $spreadsheet->getActiveSheet();
```
in PhpSpreadsheet

And you can then write values to Cells in `$activeWorksheet` (`Sheet1`).

---

To create a new Worksheet in MS Excel, you click on the "+" button in the Worksheet Tab Bar. MS Excel will then create a new Worksheet ("Sheet2") in the Spreadsheet, and make that the current "Active" Worksheet.

![image](https://user-images.githubusercontent.com/770298/223726286-edcaf4b7-bb5d-4cab-9f75-5b635d7d1338.png)

Excel always shows the "Active" Worksheet in the Grid, and you can see which Worksheet is "Active" because it is highlighted in the Worksheet Tab Bar at the bottom of the Worksheet Grid.

This is the same as
```
$activeWorksheet = $spreadsheet->createSheet();
```
in PhpSpreadsheet.

And you can then write values to Cells in `$activeWorksheet` (`Sheet2`).

---

To switch between Worksheets in MS Excel, you click on the Tab for the Worksheet that you want to be "Active" in the Worksheet Tab Bar. Excel will then set that as the "Active" Worksheet.

![image](https://user-images.githubusercontent.com/770298/223726506-8cc2280b-ab98-4179-ab72-61d0006ed751.png)

In PhpSpreadsheet, you do this by calling the Spreadsheet's `setActiveSheetIndex()` methods.
Either
```php
$activeWorksheet = $spreadsheet->setActiveSheetIndexByName('Sheet1');
```
using the name/title of the Worksheet that you want as the "Active" Worksheet

or
```php
$activeWorksheet = $spreadsheet->setActiveSheetIndex(0);
```
Where you set the "Active" Worksheet by its position in the Worksheet Tab Bar, with 0 as the first Worksheet, 1 as the second, etc.

And you can then write values to Cells in `$activeWorksheet` (`Sheet1` again).

---

Unlike MS Excel, where you can only update Cells in the "Active" Worksheet; PhpSpreadsheet allows you to update Cells in any Worksheet:
```php
$spreadsheet = new Spreadsheet(); // The Spreadsheet is created, with Worksheet Sheet1, which is the Active Worksheet
$worksheet1 = $spreadsheet->getActiveSheet(); // Assign the Active Worksheet (Sheet1) to $worksheet1
$worksheet2 = $spreadsheet->createSheet(); // Create a new Worksheet (Sheet2) and make that the Active Worksheet

$worksheet1->setCellValue('A1', 'I am a cell on Sheet1');
$worksheet2->setCellValue('A1', 'I am a cell on Sheet2');
```
Sheet2 is still the "Active" Worksheet, but you can set cells in either Worksheet without changing the "Active" Worksheet.

**Comment by MarkBaker** [comment]
> What then if suddenly the product does not have a picture, it is necessary to insert some other one? It's just that when downloading a file, an error occurs and the file cannot be opened, but when you save the file to the server, the file opens perfectly without errors

Those Warning messages are being written to PHP output. When you save the Spreadsheet file to the server, that output is displayed "on screen"; but it doesn't affect the binary data that is written to the file on the server.
But if you save the file to "php::/output" they are still written to PHP output but because you are also sending the binary stream of the file that is being written to PHP output, they are embedded in that stream. This corrupts the data in the binary stream, resulting in a file that will error and can't be opened.

You have two options
 - Tell PHP not to display Warnings. (NOT recommended, Warnings are there to tell you there is something that you need to fix)
 - Stop the Warnings by fixing the problem

If the product doesn't have a picture, then either don't create the Drawing object in PhpSpreadsheet, or use a blank image instead.
