### ISSUE TITLE
Cell::getValue() does not return raw value with numbers

### ISSUE THREAD

**Issue by Raphhh** [PHPOffice/PhpSpreadsheet#352]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

In any case, the method Cell::getValue() should not cast the value of the cell but should return only string value as stored in the file.

The int/float value should be given only in the method Cell::getFormattedValue().

### What is the current behavior?

Cell::getValue() casts the value of cell as integer/float even if the cell contents digits that not represent a number.

That causes also a lost of precision with big int.

### What are the steps to reproduce?

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$value = '10210303648605466'; //this is not a number but a string

$filePath = __DIR__ . '/example.csv';
file_put_contents($filePath, $value);

$spreadSheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($filePath);

var_dump($spreadSheet->getActiveSheet()->getCell('A1')->getValue() === $value); //should be bool(true) but display bool(false)
```

### Which versions of PhpSpreadsheet and PHP are affected?
My env:

    - PHP:7.2.1-1+ubuntu14.04.1+deb.sury.org+1PHP
    - phpoffice/phpspreadsheet:1.0.0

**Comment by PowerKiKi** [comment]
The current behavior is meant for the most common use-cases. If you need advanced needs, you should rely on a custom value binder as described in the docs: http://phpspreadsheet.readthedocs.io/en/develop/topics/reading-files/#a-brief-word-about-the-advanced-value-binder

**Comment by Raphhh** [comment]
Ok thanks for this point of the doc. 

So, there is a mistake in the doc: http://phpspreadsheet.readthedocs.io/en/develop/topics/accessing-cells/#retrieving-a-cell-value-by-coordinate indicates that "getValue" returns a "raw" value. But it is not the case because "getValue" returns a casted value as a number if digits are detected (raw value from a file must always be a string).

Maybe it should be interesting in the future to implement a complementary method "Cell::getRawValue()" that always returns the string value as found in the file.

**Comment by PowerKiKi** [comment]
"raw" might be up to debate, but in this case it is "raw" as opposed to "calculated" as seen in `getCalculatedValue()`. Please free to suggest a PR if you see a way to improve it.

**Comment by SlowFox71** [comment]
I found this issue because I was constantly reading big integers in a file that should not contain any numbers at all. Turned out that product numbers like "530E08" are recognized as scientific numbers and converted into 53000000000.

In my eyes this is really unexpected behaviour, if one only sticks to the documentation. (And besides I doubt that this should be converted at all. Nobody would ever write 530E08 but rather 5.3E10.

Perhaps a very simple handler (interpreting everything as a string) could be added and optionally be used at file opening?

**Comment by riconeitzel** [comment]
The Problem CANNOT be fixed with a custom value binder as it already happens in the XLSX reader!

\PhpOffice\PhpSpreadsheet\Reader\Xlsx:980

```php
// read empty cells or the cells are not empty
if ($this->readEmptyCells || ($value !== null && $value !== '')) {
    // Check for numeric values
    if (is_numeric($value) && $cellDataType != 's') {
        if ($value == (int) $value) {
             $value = (int) $value;
        } elseif ($value == (float) $value) {
             $value = (float) $value;
        } elseif ($value == (float) $value) {
             $value = (float) $value;
        }
}
```

**Comment by riconeitzel** [comment]
… and if you want to create a custom version of the XLSX reader YOU HAVE TO COPY THE WHOLE CLASS because WAY TOO MUCH used methods are … PRIVATE!!! 😂 

But yeah - it works!

**Comment by SlowFox71** [comment]
Actually this is not a problem with XLSX, because it comes with a type definition - if I mark a cell as "text" in Excel it is read as text here => fine.

There *is* a problem with CSV files which by definition cannot contain any meta information. If I write "530E08" into a CSV file nobody an *know* whether it should be a string or a number. 

Problem is: If the content is treated as a number, there is no way for the user of the package to revert to the string representation again (as this is ambiguous, "5300E7", "530E08", "53E09" etc). If anything (but perhaps [1-9][0-9]+) would be treated as a string, the user could still decide what to do with the result.

Therefore I consider this to be a bug in the CSV reader.

**Comment by PowerKiKi** [comment]
@SlowFox71 your issue is described in detail in #1132

**Comment by Brandyparty** [comment]
@riconeitzel is correct - the error already happens in the reader. I do not know how to fix this with the current phpoffice. It CHANGES DATA upon reading. This completly destroys any use i had for this tool. Why is there no way to get the actual raw data?

**Comment by lserni** [comment]
It is possible to "fix" this in the Xls reader class, adding a dirty kludge.

The problem is that a number above 1E+9 will by default be taken in as a _floating point_ value, then _returned as string_, and this loses precision. At the same time this only happens with **numeric values formatted as text**, and Excel will glaringly destroy values above 8999999999999999; the Excel user will notice, so we needn't worry about that.

In the interval between 1E+9 (or any other) and 8999999999999999, you can choose to have the Xls reader directly return a typed string, converted back into an integer representation. PHP precision allows this (but better check in your php.ini).

So:

1. Excel user enters "2023102712062101"
2. Excel displays "2,0231E+15" (or even "2023102712062101") but internally loses no precision
3. Xls reader reads 2,023102712062101E+15 in both cases, without loss of precision
4. Xls reader _would_ return the string "2,0231E+15" as a string, losing precision (it would mean 2023100000000000).
5. **With** this modification, the reader converts 2,023102712062101E+15 to 2023102712062101 and returns "2023102712062101" as a string
6. Profit.

It would also be possible, albeit less efficient, to get the numValue that Xls would have returned, convert it to string, cast back to float, and sprintf as integer. If it is the same as the numValue sprintfed as integer, then no precision loss occurs and it is safe to not engage the ugly kludge, and return a numeric type. If they're different, then chances are overwhelming that the number was intended as a string identifier.

```
    private function readNumber(): void
    {
        $length = self::getUInt2d($this->data, $this->pos + 2);
        $recordData = $this->readRecordData($this->data, $this->pos + 4, $length);

        // move stream pointer to next record
        $this->pos += 4 + $length;

        // offset: 0; size: 2; index to row
        $row = self::getUInt2d($recordData, 0);

        // offset: 2; size 2; index to column
        $column = self::getUInt2d($recordData, 2);
        $columnString = Coordinate::stringFromColumnIndex($column + 1);

        // Read cell?
        if (($this->getReadFilter() !== null) && $this->getReadFilter()->readCell($columnString, $row + 1, $this->phpSheet->getTitle())) {
            // offset 4; size: 2; index to XF record
            $xfIndex = self::getUInt2d($recordData, 4);

            $numValue = self::extractNumber(substr($recordData, 6, 8));

            // UGLY KLUDGE
            if ($numValue > 100000000 && $numValue <= 8999999999999999) {
                $numValue = sprintf('%d', $numValue);
                $type     = DataType::TYPE_STRING2; // Not sure of TYPE_STRING or TYPE_STRING2
            } else {
                $type     = DataType::TYPE_NUMERIC;
            }
            // END UGLY KLUDGE

            $cell = $this->phpSheet->getCell($columnString . ($row + 1));
            if (!$this->readDataOnly && isset($this->mapCellXfIndex[$xfIndex])) {
                // add cell style
                $cell->setXfIndex($this->mapCellXfIndex[$xfIndex]);
            }
            // add cell value
            $cell->setValueExplicit($numValue, $type /* MODIFIED BY UGLY KLUDGE ABOVE */ );
        }
    }

```
