### ISSUE TITLE
laravel10 installation error, please help me solve this problem, thank you

### ISSUE THREAD

**Issue by wangtao0135** [PHPOffice/PhpSpreadsheet#3558]

**Comment by tvaughan73** [comment]
might help a bit if you post what the error is.

**Comment by wangtao0135** [comment]
> might help a bit if you post what the error is.

laravel10 supports php8.1 and phpoffice supports php8.0. Can you upgrade the version 8.1 supported by PHP

<img width="1372" alt="error message" src="https://github.com/PHPOffice/PhpSpreadsheet/assets/132800646/eaacf339-f54b-495d-af0c-08772248236b">

**Comment by wangtao0135** [comment]
laravel10 supports php8.1 and phpoffice supports php8.0. Can you upgrade the version 8.1 supported by PHP，Is it compatible with the next version？Thank you very much

<img width="1372" alt="laravel php8 1" src="https://github.com/PHPOffice/PhpSpreadsheet/assets/132800646/a9e3a115-72b4-46b2-a84c-abaf68170ccd">

**Comment by MarkBaker** [comment]
PhpSpreadsheet dos support PHP 8.1, and 8.2 as well.

Your problem is with `psr/simple-cache` being fixed at version 3.0

`simple-cache` 3.0 adds typehints and return types (including "mixed") which isn't compatible with all the PHP versions we support.

Either downgrade `psr/simple-cache` to version 2.x
or try installing using
`composer require maatwebsite/excel  --with-all-dependencies`

**Comment by risky2k1** [comment]
same issue happen to me, and `composer require phpoffice/phpspreadsheet -W` did help

**Comment by Ph0tonic** [comment]
The next release should solve your problem as #3410 as been merged.

**Comment by Ph0tonic** [comment]
> Any idea when the next release is? I would rather not downgrade and lose type support

I have no idea, maybe @MarkBaker or @oleibman will be able to answer.

**Comment by Ph0tonic** [comment]
As a new release has been deployed 🔥, this issue should now be resolved and closed.
