### ISSUE TITLE
Question: is this Php 5.3 compatible? (Was it ever tested?)

### ISSUE THREAD

**Issue by magcus** [PHPOffice/PhpSpreadsheet#36]
I know in the documentation it says that this project is Php 5.5+.
I want to include this on a system that has legacy instances and these are Php 5.3.

was it ever tested on php 5.3?

**Comment by MarkBaker** [comment]
No, nor will it be.... PHPExcel has been shackled for years by being forced to provide backward compatibility for unsupported versions of PHP.... the whole point of PHPSpreadsheet is to take a deliberate step away from that ball and chain, and work only with supported versions of PHP, giving us the opportunity to work with newer features of PHP, to improve speed and memory usage, etc.

As we say in the ReadMe:

**PHP version support**

Support for PHP versions will only be maintained for a period of six months beyond the end-of-life of that PHP version

**Comment by elieobeid7** [comment]
@MarkBaker I just want to thank you I hope you get to read this, because you made the transition from phpExcel to phpspreadsheet so easy, without any tools.

I first wrote the spreadsheet using phpspreadsheet, didn't work on our servers, we run php 5.3 on centos 6 and can't upgrade, I tried downgrading to phpspreadsheet 1.8.2 which runs perfect on php 5.6 still wasn't enough.

went back to phpexcel and to my surprise I was able to do that very fast, very fast, and my excel sheet is very complicated, I use everything this library has to offer.

You are awesome, I'm forever grateful for the amazing library and for the ease of going from and to phpexcel to phpspreadsheet.

Thank you.
