### ISSUE TITLE
doc: Readme wrong link/information about suported future PHP version

### ISSUE THREAD

**Issue by sovetski** [PHPOffice/PhpSpreadsheet#3606]
This is:

- [x] a documentation error report

### What is the expected behavior?
Easy to understand which version of PHP will be supported. The "will support that version" has a global link which does not make sense.

### What is the current behavior?
Currently the required PHP minimum version is PHP 7.4, and we [will support that version](https://www.php.net/eol.php) until 28th June 2023.

**Comment by asfaqahmed** [comment]
Is there anyone who contribute to this issue?

**Comment by MarkBaker** [comment]
The LTS Support documentation says:
```
LTS: Support for PHP versions will only be maintained for a period of six months beyond the [end of life](https://www.php.net/supported-versions) of that PHP version.

Currently the required PHP minimum version is PHP 7.4, and we [will support that version](https://www.php.net/eol.php) until 28th June 2023.
```
which I had thought was fairly explicit in saying what minimum version of PHP would be supported, and until when.


The link for "will support that version" is to the list of PHP versions that are now EOL, with the date at which they reached EOL status.

I had thought it helpful so that people could see that PHP 7.4 reached EOL on 28 Nov 2022, and see that the 6 month LTS for PhpSpreadsheet from that date would be 28th June 2023.

Clearly I was mistaken, and as this is clearly considered an issue I'll remove the link, unless somebody can provide a better phrasing or an alternative link that isn't considered meaningless

**Comment by oleibman** [comment]
FWIW, I think the link is clear and useful, and should remain.

**Comment by sovetski** [comment]
Thank you @MarkBaker for the clarification.

English is not my native language, so I did not understand it correctly, sorry.

What I was understand is: "Actually we support PHP 7.4 but we will support _**THIS**_ version until ...". And for me, the "_**THIS**_" was a new future supported version, that is why I was searched the link you provided 😅

So now I understand your text, but if you want an alternative, I will say something like:

> The current minimum required PHP version is PHP 7.4. We will continue to support this version until June 28, 2023.
