### ISSUE TITLE
last 2 numbers are replaced by zeros 

### ISSUE THREAD

**Issue by han-s-kl** [PHPOffice/PhpSpreadsheet#3674]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
this string: string(18) "871822610227022011" 
should be written to xlsx exactly the same.

### What is the current behavior?
is put in my excel file as: 871822610227022000
So the last 2 digits are change into zeros'

### What are the steps to reproduce?

```php
<?php
require_once('../vendor/autoload.php');
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$filename = time();
$data =  array( 
   array( "artikel"=>     "812312310227022011",
    "description"=>     "testdesc",
    "name"=>    "testname",
    "country"=>     "UK",
    "email"=>     "test@test.com",
    "paymentId"=>     "pi_3NdJPK")
  );

	$excelFilePath = $filename.'.xlsx';

	$spreadsheet = new Spreadsheet();
	$spreadsheet->getDefaultStyle()
		->getNumberFormat()
    		->setFormatCode(
       	 	\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_NUMBER
   	 );
	$sheet = $spreadsheet->getActiveSheet();
	$headerRow = array_keys($data[0]);
	$sheet->fromArray($headerRow, null, 'A1');
	$sheet->fromArray($data, null, 'A2');
	$writer = PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xlsx');
	$writer->save($excelFilePath);

```

### What features do you think are causing the issue

- [ ] Reader
- [x ] Writer
- [x] Styles
- [x] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
xlsx and xls

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 8.2
PhpSpreadsheet 1.29.0

**Comment by MarkBaker** [comment]
Nothing to do with the Writer.

If you set a numeric string in a cell in PhpSpreadsheet, then the default behaviour is to convert that string to a number, and that is susceptible to rounding (MS Excel does exactly the same).
If you want the value to be treated as a string, then you have to advise PhpSpreadsheet that the value is a string, so that it will be set explicitly as a string in the cell.

If you're setting the cell's value using `setValue()`, then use `setValueExplicit()` instead; otherwise you could use a custom Binder to override that default behaviour

**Comment by han-s-kl** [comment]
ok, thanks for the advice, I have fixed it !!

**Comment by oleibman** [comment]
User seems satisfied with suggestion. Closing ticket.
