### ISSUE TITLE
PhpSpreadsheet toArray now returns only string values from Excel file

### ISSUE THREAD

**Issue by melicerte** [PHPOffice/PhpSpreadsheet#3736]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
With version 1.27.1, the cells types were somehow detected, so if a cell contained 12, it returned (int)12.

### What is the current behavior?
With version 1.29, the same cell is interpreted as a string "12".

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader = IOFactory::createReader(
      IOFactory::identify($file)
  );

  if ($reader instanceof Csv) {
      $reader->setDelimiter($csvDelimiter);
  }

  $reader->setReadDataOnly(true);

$test = $reader
            ->setReadDataOnly(true)
            ->setReadEmptyCells(false)
            ->load('/path/to/excel.xlsx')
            ->getActiveSheet()
            ->toArray();

var_dump($test);
```

Here is the excel file extracted in CSV : 
```
numberString;Entier;Float;
number1;12;3,5;
```

If I execute this code in 1.27.1, I get : 
(string) "number1"
(int) 12
(float) 3.5

If I execute this code in 1.29, I get : 
(string) "number1"
(string) "12"
(string) "3.5"

I expect the same behaviour between version 1.27 and 1.29

### What features do you think are causing the issue

- [ X] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
I don't know.

### Which versions of PhpSpreadsheet and PHP are affected?
1.29, didn' try with 1.28 though

**Comment by oleibman** [comment]
Regression was intentional, caused by PR #3304. The break is documented in CHANGELOG.md, but, unfortunately, in the wrong place (with the 27.0 notes rather than the 28.0 notes). Consequently, it doesn't show up in the release notes at all. I will correct that as best I can.

The cells are stored correctly in PhpSpreadsheet. It is only the behavior of the `toArray` function which has changed. That comes with several optional arguments, including `formatData`, which defaults to `true`, meaning that all data will be returned as formatted strings. To get the behavior you are looking for in any release,
change `toArray()` to `toArray(formatData: false)` or `toArray(null, true, false)`.

**Comment by melicerte** [comment]
Thank you so much @oleibman ! 
It's working :)
