### ISSUE TITLE
COUNTIFS Formula has a prefix in Excel =_xlfn.countifs

### ISSUE THREAD

**Issue by BenjaminG1983** [PHPOffice/PhpSpreadsheet#3819]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Create with PHP the formula:
$oWorkSheet->getCell([7, $iRow])->setValue("=COUNTIFS('XX'!K:K,A" . $iRow . ",'XX'!C:C,G3)");

### What is the current behavior?
Formula in Excel =**_xlfn.countifs**($XX.K:K;A4;$XX.C:C;G3)
For COUNTIF - it replaced to ZÄHLENWENN (Germany)

### What are the steps to reproduce?
1. Create a formula with COUNTIFS in PHP
2. Result in Excel, see stept before
Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$spreadsheet->getCell([7, 1])->setValue("=COUNTIFS('XX'!K:K,A1,'XX'!C:C,G1)");

If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [X] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
XLSX

### Which versions of PhpSpreadsheet and PHP are affected?
1.29.0

**Comment by oleibman** [comment]
I am not sure what your issue is. Starting with Excel 2010, Microsoft decided that new functions required prefix `_xlfn`. Starting with Office 365, it decided that some functions needed a second prefix `_xlws`. These are generally hidden from the end-user since the only time they are needed is when loading a file; if a required prefix is lacking at that time, it will show the cell's value as an error. The `COUNTIF` function was introduced before Excel 2010, so it doesn't have a prefix; the `COUNTIFS` function was introduced with 2019, so it does.

So, if you are just asking for an explanation, that's it. However, if you are having a problem because of this, possibly due to your different locale, please give more details on what the problem is.

Supplementary note - I believe our classification that COUNTIFS was introduced with 2019 was incorrect, and that it was available with 2007 and doesn't need a prefix; however the addition of xlfn would still be required for many other functions. I will look into removing COUNTIFS from our list.
