### ISSUE TITLE
Dom Element Doesn't Load if It Contains & Sign

### ISSUE THREAD

**Issue by arif98741** [PHPOffice/PhpSpreadsheet#3844]
This is:
```
- [ ] a bug report
```

### What is the expected behavior?
Excel file should be generated and downloaded.

### What is the current behavior?
I am making a spreadsheet using laravel maatwebsite/excel. This packge is dependent on PhpSpreadsheet. I was stuck for day long. Finally I found that my table heading contains **&** character. For this reason, I was getting below error

`Failed to load D:\\laragon\\www\\project\\storage\\framework\\laravel-excel\\laravel-excel-fv6jmsKIkAKXbjUBJTd36gAntw3HWMcN.html as a DOM Document`

### What are the steps to reproduce?
I generated collection , passed to view and render html document. 

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer

### Which versions of PhpSpreadsheet and PHP are affected?
`phpoffice/phpspreadsheet": "^1.18`
`PHP: 8.2.0`

**Comment by oleibman** [comment]
I'm not sure what you mean by "table heading contains & character". At a guess, I took samples/Table/01_Table.php. I modified it so that the first column was `Ye&ar` rather than `Year`, and it produced Html output which opens in a browser just fine. (Note - I did have to change the `setTitle` statement to use something shorter, but that's a different problem, which I will fix, not related to yours.) I then loaded that Html file in PhpSpreadsheet (no problem), saved it to another Html file (no problem opening in a browser or in Excel). So I need more information from you to figure out why you are having a problem.
