### ISSUE TITLE
ver 1.29 ) Csv auto_detect_line_endings

### ISSUE THREAD

**Issue by KIMKYEONGYONG** [PHPOffice/PhpSpreadsheet#3960]
This is:

```
- [ V] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

my php version 8.1 , 8.1 is <auto_detect_line_endings>method deleted!

**Comment by MarkBaker** [comment]
In PHP 8.1, the auto_detect_line_endings INI directive has been ___deprecated___, not deleted.

**Comment by MarkBaker** [comment]
There should be no error in this code, and that line should not generate any error.

What is the exact error message that you are getting?

**Comment by oleibman** [comment]
I have seen cases where user-supplied error handlers have inappropriately detected and converted the suppressed deprecation message to an error despite the use of the at-sign to suppress messages. That is the reason for the check on `testAutodetect` in the code cited above. Users unwilling to correct their error handler can add `$reader->setTestAutodetect(false)` to their code before loading the spreadsheet; they will prematurely lose the ability to detect Mac line endings (which is very unlikely to be an issue), and the error message will go away because ini_set will not be called.
