### ISSUE TITLE
mime_content_type() has been removed since PHP ver. 8

### ISSUE THREAD

**Issue by dreamsavior** [PHPOffice/PhpSpreadsheet#3963]
This is:
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the current behavior?
Attempting to load a spreadsheet file results in a fatal error due to a flaw in the MIME type testing within the code located at this line:
https://github.com/PHPOffice/PhpSpreadsheet/blob/064052b7280169eedce60dbfee7637bee6d1283e/src/PhpSpreadsheet/Reader/Csv.php#L479

### Step to reproduce
Execute the following code with the latest PHP version:
```PHP
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($filePath);
```

### Which versions of PhpSpreadsheet and PHP are affected?
- PhpSpreadsheet ver. 2.0
- PHP >= 8

Some proof:
<img width="390" alt="image" src="https://github.com/PHPOffice/PhpSpreadsheet/assets/1912407/dc21458d-4182-425e-94e7-cd04da92e2b4">

Related issue:
https://github.com/PHPOffice/PhpSpreadsheet/issues/429

**Comment by oleibman** [comment]
You are mistaken. Function mime_content_type is not removed; it is not even deprecated. It does, however, require that the fileinfo extension be loaded. That extension is required in our composer.json. It is not, however, loaded in Php Sandbox, which is why you see the result you are reporting from there (you can confirm with `var_dump(extension_loaded('fileinfo'));`.
