### ISSUE TITLE
Conditional styling doesnt support color scale with number or percentage

### ISSUE THREAD

**Issue by bokrma** [PHPOffice/PhpSpreadsheet#4049]
I checked the code for getting the details of conditional styling, but seems like I cant get the color scale with number or percentage if it was inside the sheet:
[Untitled_spreadsheet_7.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/15485637/Untitled_spreadsheet_7.xlsx)

![Screenshot 2024-05-29 at 16 10 20](https://github.com/PHPOffice/PhpSpreadsheet/assets/13594276/0bbb4330-5a10-47a6-abad-9755ceaa6021)

is it gonna be supported?

**Comment by oleibman** [comment]
Thank you for the sample spreadsheet. PhpSpreadsheet is expecting the following optional xml tags:
```xml
<colorScale>
<cfvo type="min"/>
<cfvo type="percentile" val="40"/>
<cfvo type="max"/>
...
</colorScale>
```
Your sample has the following xml:
```xml
<colorScale>
<cfvo type="formula" val="25"/>
<cfvo type="max"/>
...
</colorScale>
```
The `formula` tag is obviously taking the place of `min` here. I imagine it might take the place of either of the other two as well. I need to figure out how it works, especially since, as we see in your sample, at least one of the tags can be omitted.
