### ISSUE TITLE
invalid value for $this->cellXfCollection[$pIndex];

### ISSUE THREAD

**Issue by kampfq** [PHPOffice/PhpSpreadsheet#41]
in Spreadsheet class there will be a "null" as argument "$pIndex" when applying styles.

this causes a null return value when executing $this->cellXfCollection[$pIndex] on line 900;

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue. And don't forget to mention what version of this project you are using.

**Comment by oleibman** [comment]
According to the linked PR(?), the problem was in PhpSpreadsheet::getCellXfByIndex. In the current code, the parameter for that function is now typed as `int`. According to Php's coercion rules for non-strict, null will be coerced to 0 in this situation. So the problem is now resolved. Removing stale and help wanted labels, but leaving issue closed.
