### ISSUE TITLE
[Bug]: Incorrect definition of date data type

### ISSUE THREAD

**Issue by Kladislav** [PHPOffice/PhpSpreadsheet#4135]
https://github.com/SpartnerNL/Laravel-Excel/issues/4180

**Comment by oleibman** [comment]
What do you think is wrong? Dates are stored as floating point numbers in Excel. So, for example, the value stored in cell B3 *is* 45354. The *formatted* value of the cell is "3/3", because the number format of the cell is "d/m". If you are using `getValue` to determine the value of the cell, perhaps you should be using `getFormattedValue` instead.
