### ISSUE TITLE
Converting Excel-date numbers below 60 yields different dates compared to =TEXT(thenumber, "yyyy-mm-dd")

### ISSUE THREAD

**Issue by motin** [PHPOffice/PhpSpreadsheet#424]
This is:

```
- [x] a bug report
- [ ] a feature request
```

### What is the expected behavior?

When converting/formatting "Excel-date numbers" to dates, the result should be the same as ´=TEXT(thenumber, "yyyy-mm-dd")´.

Negative numbers and 0 should yield a date that is 1899-12-30 minus the number in days.
0 should yield 1899-12-30.
Positive numbers 1+ shuld yield a date that is 1899-12-30 plus the number in days.

### What is the current behavior?

Negative numbers yields a date that is 1970-01-01 minus the number in days.
0 yields 1970-01-01.
Positive numbers 1-59 yields a date that is one day different from the expected value.
Positive number 60+ are ok.

### What are the steps to reproduce?

Here is a spreadsheet showing the expected values and PhpSpreadsheet's values side by side: https://docs.google.com/spreadsheets/d/1fzIAYu2ss2NW0okaqAH2XDIWHJ1WrcexlVUYkZ-a_-s/edit#gid=0

To reproduce the incorrect date conversions, add this to `tests/data/Style/NumberFormatDates.php`:
```php
<?php
    [
        '1969-12-31',
        -1,
        'yyyy-mm-dd',
    ],
    [
        '1970-01-01',
        0,
        'yyyy-mm-dd',
    ],
    [
        '1900-01-01',
        1,
        'yyyy-mm-dd',
    ],
    [
        '1900-01-05',
        5,
        'yyyy-mm-dd',
    ],
    [
        '1900-01-10',
        10,
        'yyyy-mm-dd',
    ],
    [
        '1900-02-19',
        50,
        'yyyy-mm-dd',
    ],
    [
        '1900-02-24',
        55,
        'yyyy-mm-dd',
    ],
    [
        '1900-02-25',
        56,
        'yyyy-mm-dd',
    ],
    [
        '1900-02-26',
        57,
        'yyyy-mm-dd',
    ],
    [
        '1900-02-27',
        58,
        'yyyy-mm-dd',
    ],
    [
        '1900-02-28',
        59,
        'yyyy-mm-dd',
    ],
    [
        '1900-02-28',
        60,
        'yyyy-mm-dd',
    ],
    [
        '1900-03-10',
        70,
        'yyyy-mm-dd',
    ],
    [
        '1900-03-20',
        80,
        'yyyy-mm-dd',
    ],
    [
        '1900-03-30',
        90,
        'yyyy-mm-dd',
    ],
    [
        '1900-04-09',
        100,
        'yyyy-mm-dd',
    ],
```

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet - latest develop branch as of a reporting this issue. PHP 7.2.2

**Comment by PowerKiKi** [comment]
Thank you for this excellent bug report. Would you be able to suggest a PR to fix it ?

**Comment by oleibman** [comment]
Excel is buggy for dates below 1900-03-01, and does not really support dates before 1900 at all. PhpSpreadsheet is, for better or worse, bug-compatible with Excel in this regard. Google Sheets is not bug-compatible. If you want to be compatible with Sheets rather than Excel, you can always use:
```php
use PhpOffice\PhpSpreadsheet\Calculation\Functions;
Functions::setCompatibilityMode(Functions::COMPATIBILITY_OPENOFFICE);
```
(Caveat - functions other than Dates are affected by this switch.)

You raise an interesting point in that 0 and negative values cause the use of a 1970 base date in PhpSpreadsheet, which does not correspond to Excel or anything else that I am aware of. I am not privy to the reasons for that decision made long, long ago. Changing the Compatibility as above eliminates that problem. If someone is unhappy with both the current result and the suggested workaround, I will be glad to discuss the matter with them in a new issue.
