### ISSUE TITLE
Image and gray disappear after IOFactory::createWriter and save

### ISSUE THREAD

**Issue by kboumedal** [PHPOffice/PhpSpreadsheet#4248]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the current behavior?

Image and gray disappear after IOFactory::createWriter and save

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
        $spreadsheet = IOFactory::load(
[Tool choix subventions  - GMS_simulateur_eau-déchets.xlsx](https://github.com/user-attachments/files/17946990/Tool.choix.subventions.-.GMS_simulateur_eau-dechets.xlsx)
);

$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');

$temporaryPathfile = rtrim(sys_get_temp_dir(), \DIRECTORY_SEPARATOR).\DIRECTORY_SEPARATOR.md5(uniqid().mt_rand());

$writer->save($temporaryPathfile);

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet 3.4, PHP8.3

**Comment by oleibman** [comment]
I have downloaded your spreadsheet, and used PhpSpreadsheet to load and save it to a new file. Except for one svg image (we do not handle svg), all the images and the gray backgrounds are present in the output file. What do you think is missing? It might help if you upload your output file so that I can see where it differs from mine.

**Comment by kboumedal** [comment]
Here is the after/before comparison, you can see some gray is missing on the left pane
<img width="779" alt="image" src="https://github.com/user-attachments/assets/044708c4-b249-48cf-bd9e-3e81d23c2c08">

**Comment by oleibman** [comment]
Ah, yes, sorry I missed that. I will see what I can find.

**Comment by oleibman** [comment]
Looks like another simple problem that will be difficult to solve. Every fill style has a start color and an end color, which the constructor by default initializes to white and black. And what documentation there is always shows the Xml containing both a start and and end color. So, what's in your spreadsheet? Several fill styles with an end color and no start color. In the case of the "darkDown" pattern (and certainly other patterns), which is what the cells in question use, the start color is used as the color of the dots or stripes or whatever distinguishes this pattern from the other possibilities. When the start color is omitted, Excel uses an "automatic" color. In this case, the automatic color is black (I have no idea if this is always the case), but since we initialize the color to white, that's what is being used, and why you see a discrepancy between your input and output files. So I need to find a way to implement automatic colors in a manner which fixes your case without causing compatibility breaks for others. It could take a while.

If you truly need this fixed while I am working on a solution, you could iterate through all the styles, and change the start color for darkdown patterns from white to black. I can supply code to do this if you need it.

**Comment by oleibman** [comment]
It appears that background color can also be omitted, and pattern type can be omitted in conditional styles.
