### ISSUE TITLE
Unable to read CSV file because of false postive in mime type detection.

### ISSUE THREAD

**Issue by ravibpatel** [PHPOffice/PhpSpreadsheet#429]
## What is the expected behavior?

CSV file should be readable even if the mime type of the file doesn't match.

## What is the current behavior?

When I try to read a CSV file PhpSpreadsheet was unable to read it cause canRead function returns false.
I am getting "text/x-fortran" as a mime type for my CSV file. 

## What are the steps to reproduce?

You can find CSV file [here](https://we.tl/3RPMfwtIeB).

## Possible solution to the problem.

https://github.com/PHPOffice/PhpSpreadsheet/blob/064052b7280169eedce60dbfee7637bee6d1283e/src/PhpSpreadsheet/Reader/Csv.php#L479

I suggest you should not rely on this function to test the file. I removed the mime type check and it was able to read the file successfully with "," as a Delimiter.

## Which versions of PhpSpreadsheet are affected?

PhpSpreadsheet 1.2.0

**Comment by xsdhy** [comment]
I had the same problem.
Call to undefined function PhpOffice\PhpSpreadsheet\Reader\mime_content_type() in /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Csv.php:479

**Comment by ravibpatel** [comment]
@xsdhy You can fix it by removing following lines from the file.

https://github.com/PHPOffice/PhpSpreadsheet/blob/064052b7280169eedce60dbfee7637bee6d1283e/src/PhpSpreadsheet/Reader/Csv.php#L479-#L486 

and replace it with "return true".

**Comment by xsdhy** [comment]
@ravibpatel  ok，thanks
Hopefully the author can fix this bug as soon as possible.

**Comment by xsdhy** [comment]
I found that this was not a bug, or that it was not a particularly serious bug.
The reason I got this bug was that a file suffix named excel2007 was changed to XLS.

**Comment by abunch** [comment]
+1 - same issue here

**Comment by abunch** [comment]
Instead of editing the source, we just locked our version to 
dev-master#fb5f8d4763962f1c464b44b2788871903edc43ed

That version successfully recognizes and imports .csv files with no issues - it's the December 23, 2017 release (fb5f8d4763962f1c464b44b2788871903edc43ed)  just prior to the 1.0 release.  I could probably have used a newer check-in than that but I don't have time at the moment to work backwards through the check-ins to figure out where this broke.

IMO this is a better solution than directly editing the code.

**Comment by PowerKiKi** [comment]
@ravibpatel, we must test somehow that it is some kind of CSV looking file. Otherwise we are back at #167 where CSV reader tried to parse any kind of file, including binary one, and failed in all sort of miserable ways. What we could do though is trust the file extension if it is CSV and hope for the best. And if it is not, then fallback to mime detection.

@xsdhi your issue is that you miss the PHP extension for mime. You should install it, and we should declare it as a dependency.

@abunch, the change was introduced on 1.2.0, https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.2.0. So you should be able to safely pin 1.1.0

**Comment by topclaudy** [comment]
Any update on this?

**Comment by yupmin** [comment]
I think you should change this. 'mime_content_type' in 'canRead' is unsafe.

/src/PhpSpreadsheet/Reader/Csv.php

```
    public function canRead($pFilename)
    {
        ...
        // Trust file extension if any
        if (strtolower(pathinfo($pFilename, PATHINFO_EXTENSION)) === 'csv' ||
            strtolower(pathinfo($pFilename, PATHINFO_EXTENSION)) === 'tsv'
        ) {
            return true;
        }
       ...
```

**Comment by MGParisi** [comment]
Im also having an issue.  The problem is not fixed with an early true.

**Comment by dreamsavior** [comment]
Strictly speaking this is not PhpSpreadsheet's problem, but your PHP version problem.
`mime_content_type` was marked as deprecated on PHP 7. And was probably removed on latter version of PHP.

So, to tackle this problem you can just polyfill the `mime_content_type` with the more recommended way to detect file type, which is using `finfo` library (make sure finfo library exist and is activated in your `php.ini`). Then put this script somewhere in your main script before you execute phpSpreadsheet :
```php
if(!function_exists("mime_content_type")) {
	function mime_content_type($path) {
		// Create a FileInfo object
		$finfo = finfo_open(FILEINFO_MIME_TYPE);

		// Get the MIME type of the file
		$mime_type = finfo_file($finfo, $path);

		// Close FileInfo resource
		finfo_close($finfo);

		return $mime_type;
	}
}
```


As for improvement for the PhpSpreadsheet itself, I suggest to migrate from `mime_content_type` to `finfo` library.

**Comment by oleibman** [comment]
Function mime_content_type is neither removed nor deprecated.

**Comment by oleibman** [comment]
Csv Reader now passes files with csv or tsv extension, which is probably good enough. Unable to download file associated with this issue any longer. However, if someone has a new file with this problem, please open a new issue.
