### ISSUE TITLE
Handling issues/PRs in PHPExcel and which branch is stable?

### ISSUE THREAD

**Issue by Quix0r** [PHPOffice/PhpSpreadsheet#45]
There are currently over 440 issues and over 130 PRs which seem to be not handled due to that PHPExcel is obsolete (in favour of PHPSpreadsheet). To avoid that people keep running to the old project and report there, issues and PRs should be closed and noted that development does now happen here (PHPSpreadsheet).

I also wonder that is the latest stable branch over there? For example 1.8 has one commit more than develop which is normally not the case (as developer branches are mostly ahead of release branches).

**Comment by PowerKiKi** [comment]
PR are more than welcome here, and I am trying to close/merge here PR from PHPExcel as much as possible. But for issues, I feel it's a bit early to accept them, because PhpSpreadsheet was never released yet, not even as an alpha. 

@MarkBaker any thoughts on that ? should we close all PHPExcel issues ? also should we be more strict and reredirect to StackOverflow instead of this issue tracker to try and keep the issue volumes low ?

As for branches and tags, they've been cleaned up a while ago,  try `git remote prune origin` to update your local branches. Basically there is only `develop` branch for now.

**Comment by Quix0r** [comment]
**TIL:** _master_ is staging, _develop_ is latest developer code.

**Comment by PowerKiKi** [comment]
> The master branch only contains tagged releases

from https://github.com/PHPOffice/PhpSpreadsheet#want-to-contribute

But since we don't have any tagged release yet, it is not used at all.

**Comment by Gemorroj** [comment]
Any news?
Need to stabilize the API to start to move to a new library.

**Comment by PowerKiKi** [comment]
The [1.0](https://github.com/PHPOffice/PhpSpreadsheet/milestone/1) milestone should give you an indication of progress. But unfortunately it may not be as exhaustive as I would like it to be, because I think @MarkBaker still has a few ideas for v1.0 that he didn't write down.

Anyway, help is very much welcome to push things forward.

**Comment by PowerKiKi** [comment]
I'm gonna close this, because I don't plan to do anything about PHPExcel anymore. The project is soon to be dead, and I don't think that notifying 500+ people about it is a good idea.
