### ISSUE TITLE
Chunk Read returning empty rows

### ISSUE THREAD

**Issue by netstudenton** [PHPOffice/PhpSpreadsheet#477]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
An array of chunk with no empty rows

### What is the current behavior?
After `var_dump` the results some of the rows are empty even though my excel file has no empty rows

### Filter
```
class ChunkReadFilter implements IReadFilter
{
private $startRow = 0;
private $endRow   = 0;

// Set the list of rows that we want to read  
public function setRows($startRow, $chunkSize) {
    $this->startRow = $startRow;
    $this->endRow   = $startRow + $chunkSize;
}

public function readCell($column, $row, $worksheetName = '') {
    //  Only read the heading row, and the configured rows
  // if (($row == 1) || ($row >= $this->startRow && $row < $this->endRow)) {
 if (($row >= $this->startRow && $row < $this->endRow)) {
        if (in_array($column, range('A', 'L'))) {
            return true;
        }

    }
    return false;
}
}
```
### Code
```
$inputFileType = 'Xlsx';
$inputFileName = $path;

$reader = IOFactory::createReader($inputFileType);
$chunkSize = 100;
$chunkFilter = new ChunkReadFilter();
for ($startRow = 1; $startRow <= 800; $startRow += $chunkSize) {

     //Tell the Read Filter which rows we want this iteration  
    $chunkFilter->setRows($startRow,$chunkSize);
    //Tell the Reader that we want to use the Read Filter 
    $reader->setReadFilter($chunkFilter);
    //Load only the rows that match our filter  
    $spreadsheet = $reader->load($inputFileName);
    //Do some processing here
    $sheetData = $spreadsheet->getActiveSheet()
   ->toArray(null, true, true, true);

      var_dump($sheetData);
   }
```

### Which versions of PhpSpreadsheet and PHP are affected?
php: 7.2
PhpSpreadsheet :1.2

**Comment by MarkBaker** [comment]
Chunk reading doesn't populate rows that aren't included in the read filter, but it leaves them empty... that is how it is intended to work.... if you tell PHPSpreadsheet to read rows 11 to 20, then it reads the cells for rows 11 to 20.... it doesn't renumber the rows to give you 1-10. And you can still chose to access cells in rows 1 to 10 should you choose.... this is how it is intended to work.

If you want to create an array with the loaded cells, then use `rangeToArray()` for the rows that you have loaded instead of `toArray()`

**Comment by maximnl** [comment]
there is a work around this problem , u just need to remove the leading rows before the current chunk , 
using array_splice. 

for CSV you can also use $reader->loadIntoExisting($file,$spreadsheet).   instead of just load, but i finally abandoned 
this as , it did not work for excel, a bug?  

ok, here is a universal solution for all readers, but testen on excels and csv so far. 

for ($startRow = 2; $startRow <= $totalRows; $startRow += $chunkSize) {
			/**  Tell the Read Filter which rows we want this iteration  **/
			$chunkFilter->setRows($startRow,$chunkSize);
			echo "Loading rows $startRow - <br>";		
	
			$spreadsheet = $reader->load($file);
			$sheetData = $spreadsheet->getActiveSheet()->toArray(null, false, false, true);
			
			if($startRow>2){ array_splice( $sheetData ,1,$startRow-3);} 
			 // here we skip the first chunk :) ho ho.

...

...
