### ISSUE TITLE
syntax error in Calculation.php on line 3058 - php 5.6

### ISSUE THREAD

**Issue by cca220v** [PHPOffice/PhpSpreadsheet#502]
This is:

```
- [ * ] a bug report
- [ ] a feature request
- [ * ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
create a spreadsheet

### What is the current behavior?
Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php on line 3058

### What are the steps to reproduce?
```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
```

### Which versions of PhpSpreadsheet and PHP are affected?
phpspreadsheet - 1.2.1
php - 5.6.33

**Comment by cca220v** [comment]
also
`private static function mkMatrix(...$args)`
appears to be unused at the moment

**Comment by PowerKiKi** [comment]
[Variadic functions are supported since PHP 5.6](http://php.net/manual/en/migration56.new-features.php#migration56.new-features.variadics), that means PhpSpreadsheet is not ran with the PHP 5.6.33 you mentioned, but an older version. Double check your system configuration.

Also `mkMatrix` is reference as a string and thus the function may be actually used.
