### ISSUE TITLE
Formula calculation not correct for supported functions TEXT, CHOOSE, MATCH

### ISSUE THREAD

**Issue by thetreewithin** [PHPOffice/PhpSpreadsheet#518]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The variable $value should contain "20 min 50 sec"

### What is the current behavior?
The variable $value contains "0VALUE!"

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$spreadsheet->getActiveSheet()->setCellValue('A1', '=TEXT(1250/86400,CHOOSE(MATCH(1250,{0,60,3600},1),"s ""sec""","m ""min"" s ""sec""","[h] ""hrs"" m ""min"" s ""sec"""))');
$value = $spreadsheet->getActiveSheet()->getCell('A1')->getCalculatedValue();
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.1.5, PhpSpreadsheet 1.2.1

**Comment by criztovyl** [comment]
I think a little more decomposed formula would help debug the issue.

What I found so far:

|Formula|Okay?|Expected|Actual|
---|----|----|----|
`MATCH`|&times;|`2`| `N/A`
`CHOOSE`|&#10003;|`m "min" s "sec"`|`m "min" s "sec"`
 `TEXT`| &times;|`20 min 50 sec`| `1 min 50 sec`

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$spreadsheet->getActiveSheet()->setCellValue('A1', '=MATCH(1250,{0,60,3600},1)');
$spreadsheet->getActiveSheet()->setCellValue('A2',
    '=CHOOSE(2,"s ""sec""","m ""min"" s ""sec""","[h] ""hrs"" m ""min"" s ""sec""")');
$spreadsheet->getActiveSheet()->setCellValue('A3', '=TEXT(1250/86400,"m ""min"" s ""sec""")');

echo $spreadsheet->getActiveSheet()->getCell('A1')->getCalculatedValue(), PHP_EOL;
echo $spreadsheet->getActiveSheet()->getCell('A2')->getCalculatedValue(), PHP_EOL;
echo $spreadsheet->getActiveSheet()->getCell('A3')->getCalculatedValue(), PHP_EOL;
```

**Comment by oleibman** [comment]
The problem with MATCH has been resolved for some time.

The use of `m` in the text format is ambiguous. I do not know how Excel resolves it as minutes rather than months. PhpSpreadsheet will resolve it as months unless it is preceded or followed by a colon. If you were instead to use `[mm]`, both Excel and PhpSpreadsheet would resolve it as minutes.

I think that, somehow, Excel is recognizing the seconds format and therefore deciding that m must be minutes. However, if you used a format like `m "min"`, Excel would resolve the m as months. Whatever they are doing to guess minutes for the given example seems too complicated for PhpSpreadsheet in the absence of a published algorithm. Stick with the workaround above.

Removing stale tag from issue, but leaving it closed.
