### ISSUE TITLE
[BUG] Issue with conditional formatting being applied to the cell below the cell that matches the rule

### ISSUE THREAD

**Issue by u01jmg3** [PHPOffice/PhpSpreadsheet#531]
This is:

```
- [x] a bug report
```

### What is the expected behavior?

Conditionally formatting a range of cells as per the code below should format any cell beginning with the string '-'.

### What is the current behavior?

> _Conditionally formatting a range of cells as per the code below should format any cell beginning with the string '-'._

The formatting is applied but to the cell **below** the cell that begins with the string '-'.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$worksheet = $spreadsheet->getActiveSheet();

$conditional = new \PhpOffice\PhpSpreadsheet\Style\Conditional();
$conditional->setConditionType(\PhpOffice\PhpSpreadsheet\Style\Conditional::CONDITION_CONTAINSTEXT)
            ->setOperatorType(\PhpOffice\PhpSpreadsheet\Style\Conditional::OPERATOR_BEGINSWITH)
            ->setText('-');
$conditional->getStyle()->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_DARKRED);
$conditional->getStyle()->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)->getEndColor()->setARGB('FFC7CE');

$worksheet->getStyle('A:Z')->setConditionalStyles([$conditional]);

$data = [
    0 =>  [
        0 => 'Candidate Number',
        1 => 'Candidate Name',
        2 => 'Site',
        3 => 'Run',
        4 => '3. Diagnostic Procedure - ECG',
        5 => 'Global Score',
        6 => '7. Comms Resp History COPD',
        7 => 'Global Score',
        8 => 'Total',
    ],
    1 => [
        0 => 1,
        1 => 'Joe Bloggs',
        2 => '-',
        3 => '-',
        4 => 24.5,
        5 => 5,
        6 => '-',
        7 => '-',
        8 => 24.5,
    ],
];

$worksheet->fromArray($data);

header('Content-Type: application/vnd.ms-excel');
header("Content-Disposition: attachment; filename='test.xlsx'");

$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->save('php://output');
```

### Which versions of PhpSpreadsheet and PHP are affected?

`v1.2.1`

**Comment by u01jmg3** [comment]
Still a bug... happy to provide further info

**Comment by u01jmg3** [comment]
+1

**Comment by ufhy** [comment]
up

**Comment by kifni41** [comment]
just check sample code, i can confim the bug is there, but. i only tied it with Libre Office
Then i tried to changes using Libre Office conditional formatting editor, and it's seem to get what you want to achive is using "CONDITION_CELLIS", and operator "OPERATOR_BEGINSWITH".

But after i edit the code, bug still there and even no style appear. 

Still trying to debug the bug, but haven't found a walkaround.

I think the fix should be on  function _writeConditionalFormatting_ in Writer/Xlsx/Worksheet.php

Gonna need to learn about te xml standard for spreadsheet.

**Comment by kifni41** [comment]
After reading some page on ECMA 376 Office Open XML reference (i'm not 100% sure if this is the same reference MS use for their Xlsx)
https://c-rex.net/projects/samples/ooxml/e1/Part4/OOXML_P4_DOCX_cfRule_topic_ID0EFKO4.html
https://c-rex.net/projects/samples/ooxml/e1/Part4/OOXML_P4_DOCX_ST_ConditionalFormat_topic_ID0ETVFFB.html#topic_ID0ETVFFB

I almost sure that you should use CONDITION_CELLIS and OPERATOR_BEGINSWITH for your case.

I check function writeConditionalFormatting on Writer/Xlsx/Worksheet.php, and it's seem CELLIS and BEGINSWITH is not covered, so i tried to made some changes there

```php
//this branch to catch CELLIS and BEGINSWITH
elseif ($conditional->getConditionType() == Conditional::CONDITION_CELLIS
    && $conditional->getOperatorType() == Conditional::OPERATOR_BEGINSWITH
    && $conditional->getText() !== null
    ) {
    $objWriter->writeElement('formula', '"' .$conditional->getText().'"');
}
```

Unfortunately i don't have MS Office on my current machice, so i tried on Libre Office, but that doens't work there. After tried different combination and examine the xml output, i tried to open the file result on Google Sheet, and oddly it's works, then i installed WPS Office since some people said it has better Xlsx compatibility, and its also works there. 

If any of you can try to open this file and confirmed if its working or not in MS Excel that would be good.
here's the file https://www.dropbox.com/s/gkj18za4wi1p95b/Issue531PhpSpreadSheetFileTest.xlsx?dl=0

If that's works, i think we should modify writeConditionalFormatting function to cover this problem.

**Comment by u01jmg3** [comment]
MS Office Excel complains that there is an issue with the content when I attempt to open it

**Comment by u01jmg3** [comment]
Would really like to get this bug fixed. Happy to test any further fixes on my end.

**Comment by u01jmg3** [comment]
Pity, issue still exists

**Comment by oleibman** [comment]
Supplied code now generates a sheet with the expected formatting, and no complaint from Excel when opening.
