### ISSUE TITLE
Enable reader for Strict Open XML-Worksheets (xlsx)

### ISSUE THREAD

**Issue by SnakeME** [PHPOffice/PhpSpreadsheet#623]
This is:

```
- [ ] a bug report
- [x ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
PhpSpreadsheet should be able to read Strict Open XML-Worksheets (xlsx)

### What is the current behavior?
When trying to read a Strict Open XML-Worksheets (xlsx) file an Exception is thrown:

"message": "Unable to identify a reader for this file",
"exception": "PhpOffice\\PhpSpreadsheet\\Reader\\Exception",

### Which versions of PhpSpreadsheet and PHP are affected?
<= 1.3.1

**Comment by arya108** [comment]
I am getting the same error message for Microsoft OOXML and Microsoft Excel 2007+ xlsx types.  In the file **/var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php**,  the public function canRead($pFilename) calls $zip->open($pFilename), which returns "ZipArchive::ER_NOENT" (aka int 9), which means **No such file**, but the file exists and is readable because a few lines beforehand, **File::assertFile($pFilename);** returns true.  So, the problem seems to be with $zip->open (also known as **[ZipArchive::open](http://php.net/manual/en/ziparchive.open.php)**).

I belive ZipArchive::open uses the C-based zip library.  So, I downloaded the source code and did a cursory review of the file named zip_open.c, but I did not recognize any problem.  It seems doing a thorough investigation requires significantly more time/knowledge.  Hopefully, another person can figure this out and comment on this page.

**Comment by Barry-Fisher** [comment]
We were also encountering this issue and found that transforming our stream based paths (e.g. public://) to an absolute path on the filesystem, that $zip->open() successfully returned TRUE. Thanks @OIOIOOOI for the hint.

**Comment by oleibman** [comment]
Issue seems resolved based on the two preceding comments. Removing stale label, leaving issue closed.
