### ISSUE TITLE
PhpSpreadsheet generates a faulty Xls file when cells contain emojis

### ISSUE THREAD

**Issue by rzds** [PHPOffice/PhpSpreadsheet#642]
This is an old story and it only happens when generating Xls files, it doesn't with Xlsx files. The same issue in the deprecated PHPExcel https://github.com/PHPOffice/PHPExcel/issues/1320
No one said why this is happening.
The reader works fine with emojis.
Isn't this issue fixable?

**Comment by chandon** [comment]
I've got the same issue

**Comment by PowerKiKi** [comment]
I believe Xls cannot support emoji. And even if it did, you really should use xlsx which has been around for more than 10 years already

**Comment by Jurigag** [comment]
This is not true, you can normally save xls file containing emoji and then open it.

**Comment by xuanskyer** [comment]
tks all , i got same q.:)

**Comment by Daizygod** [comment]
Still not supported 💀💀💀

**Comment by oleibman** [comment]
The problem is not restricted to emojis; it affects any text which uses characters not in the Unicode BMP. For Xls, Excel encodes its characters in UTF-16, generally a double-byte character set. But, for characters outside the BMP, UTF-16 uses "surrogates" to encode the character as 2 double-byte characters. Excel stores the number of 2-byte characters (so each non-BMP character counts as 2), but PhpSpreadsheet is storing the number of characters (so each non-BMP character counts as 1). Expect a fix in a day or two.

**Comment by Daizygod** [comment]
> The problem is not restricted to emojis; it affects any text which uses characters not in the Unicode BMP. For Xls, Excel encodes its characters in UTF-16, generally a double-byte character set. But, for characters outside the BMP, UTF-16 uses "surrogates" to encode the character as 2 double-byte characters. Excel stores the number of 2-byte characters (so each non-BMP character counts as 2), but PhpSpreadsheet is storing the number of characters (so each non-BMP character counts as 1). Expect a fix in a day or two.

It`s really can be fixed? I've been thinking about switching to XLSWriter, I will wait thanks.
