### ISSUE TITLE
Limitation of IReadFilter don't work with xls file

### ISSUE THREAD

**Issue by AdryanSignor** [PHPOffice/PhpSpreadsheet#680]
Hi, this is:

```
- [X] a bug report
- [ ] a feature request
```

### What is the expected behavior?
The limitation of reading rows when loading xls file with IReadFilter interface.

### What is the current behavior?
Reading all rows when loading xls file with IReadFilter interface.

### What are the steps to reproduce?
1. Create a file with 10 rows.
2. Implements IReadFilter with row limitation 5.
3. Create an Xls reader.
4. Set the class with IReadFilter.
5. Load the xls file.
6. Get the highest row, this returns 10, not the expected 5.

```php
<?php

use \PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use \PhpOffice\PhpSpreadsheet\IOFactory;
use \PhpOffice\PhpSpreadsheet\Reader\IReadFilter;

class SpreadsheetReadFilter implements IReadFilter {

	const LIMIT_ROW = 10000;

	const LIMIT_COLUMN = 256;

	private static $instance;

	private function __construct() {}

	public static function getInstance() {
		if (self::$instance == null) {
			self::$instance = new self();
		}

		return self::$instance;
	}

	public function readCell($column, $row, $worksheetName = '') {
		//return false; // Also reading all rows
		return ($row <= self::LIMIT_ROW && Coordinate::columnIndexFromString($column) <= self::LIMIT_COLUMN);
	}
}

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = IOFactory::createReader('Xls')
	->setReadFilter(SpreadsheetReadFilter::getInstance())
	->load('./testRead.xls');

/**
 * expected: SpreadsheetReadFilter::LIMIT_ROW // 10000
 * current for Xls:  40001
 * current for Csv:  10000
 * current for Xlsx: 10000
 */
echo $spreadsheet->getActiveSheet()->getHighestRow();
```
Test files (Csv, Xls, xlsx):
[testRead.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/2392631/testRead.zip)

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.1.21
PhpSpreadsheet ^1.3

**Comment by oleibman** [comment]
I have an explanation. It is not clear to me that a fix is warranted, but I should at least reopen the issue while I am pondering.

The Filter is working as it should. After you have finished the Xls read, there are no cells in the spreadsheet above row 2. This is reflected in `highestDataRow`. What *does* exist in the spreadsheet is a `row dimension` entry for row 40001, which accounts for the `highestRow` result. Although your Xlsx spreadsheet (which, by the way, has a `highestRow` result of 2 not 10000) avoids this problem, you might see a similar result if row 40001 was styled in any way, e.g. with a non-default height. Similar considerations probably apply to filtered columns as well as rows.

IFilter, by design, filters cells, not row and column dimensions. Because it is an interface, it would be difficult to add anything which does filter the dimensions without breaking existing code. We could certainly test for the existence of dimension-filtering methods in the Filter. This would be a lot of work - Csv wouldn't need it, but most of the other readers would, probably in multiple places. We could instead add new dimension-filtering interfaces - less risk of breakage, about the same amount of work. Regardless, in the end I'm not sure we'd be better off after the additions. As explained, the current design is doing what it is supposed to. As for processing after the read is complete, we usually recommend the use of `highestDataRow/Column` rather than `highestRow/Column`.

So I am not convinced that there is a use case for filtering dimensions. I will leave this issue open for a while. If people can add to the discussion in a way that convinces me that such a use case exists, I will consider adding it.
