### ISSUE TITLE
Composer - Why force me to use it?

### ISSUE THREAD

**Issue by noxidsoft** [PHPOffice/PhpSpreadsheet#757]
This is:

```
- [ ] a bug report
- [*] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Direct download (not dependent on Composer)

### What is the current behavior?
Forced to use Composer, NPM minimal would be better or direct download/PHP file library copy

**Comment by gmsantos** [comment]
Composer is wide used for PHP projects and it is great to manage external code dependencies. I can only point in advantages to use it.

However, if you want direct download, you can go to Releases page on GitHub and download a zip: https://github.com/PHPOffice/PhpSpreadsheet/releases

**Comment by PowerKiKi** [comment]
Composer is the de-factor PHP package managers. As PhpSpreadsheet evolves, we need to depends on other packages. Composer will manage those packages automatically for you.

@gmsantos I exceptionally edited your comment because you gave instructions that could not work (unless if you know really well what you are doing, which is not the case here).

**Comment by noxidsoft** [comment]
Nearly two years later, totally forgot about this off-hand comment I made, touchy subject for some I guess. For historicity sake, I do use Composer, always have and I'm well aware of it's standing in the world. I'll leave it at that.
