### ISSUE TITLE
XXE Injection - Security scan bypass

### ISSUE THREAD

**Issue by alxjsn** [PHPOffice/PhpSpreadsheet#771]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The securityScan() function is used to prevent XXE attacks. 

### What is the current behavior?
The securityScan() function can be bypassed by using UTF-7 encoding.

### What are the steps to reproduce?

Details suppressed until patch is released

Please let me know if you would like more details on generating the xlsx file or if you need any clarification about the issue.

### Which versions of PhpSpreadsheet and PHP are affected?
I believe it affects all versions.

**Comment by MarkBaker** [comment]
Thanks for highlighting this issue. I've been reading up on UTF-7, and understand how this works, and am looking to the most efficient solution that I can find for handling charsets like UTF-7

**Comment by MarkBaker** [comment]
`libxml_disable_entity_loader()` couldn't be used originally because it it wasn't an option with the PHP versions supported by the original PHPExcel library requirement for PHP >= 5.2.0 - `libxml_disable_entity_loader()` was introduced in 5.2.11 -  and when we ported everything to PHPSpreadsheet we simply ported the `securityScan()` code as it already existed... so certainly it is an option now.
The other option that I'd consider is a charset conversion to UTF-8, which would also support xlsx files created using apps that don't use UTF-8 in the XML when creating xlsx files, but I have no idea whether such xlsx scripts actually exist.
Overall, the use of `libxml_disable_entity_loader()` is a better option in many ways; the only drawback being that it's a global setting and may have adverse effects elsewhere in an end users script if they are dealing with xml files outside of PhpSpreadsheet. Worth the risk of that, I'd probably agree.

**Comment by MarkBaker** [comment]
Looking more closely `libxml_disable_entity_loader()` was non thread-safe - [bug reference #64938](https://bugs.php.net/bug.php?id=64938) -, set globally until 2016-07-20, and still a problem with fpm until 2017-11-28. That equates to PHP versions 7.0.27 (for 7.0, EOL in 2 weeks), 7.1.13 and 7.2.1 across the three branches. That's the level of risk using it.

**Comment by MarkBaker** [comment]
Initial work done on `xxe` branch

**Comment by MarkBaker** [comment]
Fixed in version 1.5.1

**Comment by MarkBaker** [comment]
Thanks for alerting us to the vulnerability; although I would have preferred an email with the details, rather than posting an actual example publicly here, and an email would have triggered my attention sooner.

**Comment by alxjsn** [comment]
My apologies. I was unable to find a contact email or website for the project, which is why I submitted the bug through here. I will keep that in mind if I come across any issues in the future.

**Comment by zkebami** [comment]
:'( 

![image](https://user-images.githubusercontent.com/47888955/64927841-03680f00-d808-11e9-8e35-0745ee47512d.png)
