### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by unlikenesses** [PHPOffice/PhpSpreadsheet#872]
This is:

```
- [*] a bug report
- [ ] a feature request
```

### What is the expected behavior?
I am using the PhpSpreadsheet package in Laravel 5.7 to read a file:

```
$reader = IOFactory::load($filePath);
return $reader->getActiveSheet()->toArray();
```

I expect this to return an array of data from the spreadsheet.

### What is the current behavior?

I get a "Division by zero" error. The error occurs in `/app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Style/NumberFormat.php`, at line `522`:

```
$adjustedDecimalPart = $decimalPart / $GCD;
```

The offending cell seems to be one which contains `3/4` and has a `Fraction` format.

### Which versions of PhpSpreadsheet and PHP are affected?

PHP: 7.0.22
PhpSpreadsheet: 1.6.0

**Comment by oleibman** [comment]
No problem reading a spreadsheet with a cell set to `0.75` and a number format of `0/0' with current version. Interestingly, with 1.6.0, the version where this problem is reported, `getFormattedValue` returns `0/0', not `3/4`, but it doesn't throw a division by zero. That behavior continues at least through 1.18.0. However, it is fixed some time between then and 1.28.0. Based on the knowledge that it is fixed, I am leaving this issue closed, but removing the stale label.
