### ISSUE TITLE
SVERVERWEIS cause Formula Error: An unexpected error occured

### ISSUE THREAD

**Issue by lodzen** [PHPOffice/PhpSpreadsheet#889]
This is:

```
- [ x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
SVERVERWEIS Formula should work with $ in Matrix Parameter

### What is the current behavior?
When i insert a SVERVERWEIS  formula with the $ marker in the Matrix definition the getCalculatedValue() method throws an exception:
Formula Error: An unexpected error occured

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

Create a empty excel sheet with Worksheet and Tabelle1 and the **=SVERWEIS(E3;Tabelle1!$B:$D;3;FALSCH)** formula.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
        $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load("../storage/app/template/test.xlsx");     
        $sheet = $spreadsheet->getSheetByName('Worksheet');
        $sheet->setCellValue('F5', 'Test');

        $writer = new Xlsx($spreadsheet);
        $writer->save('intermediate.xlsx');

// add code that show the issue here...
```

**Comment by MarkBaker** [comment]
Formulae must be entered in en_us format (US function names, comma separators for function arguments, unless you have use Calculation engine locale settings to convert your formula to en_us

**Comment by p1ngb4ck** [comment]
Could you provide an example of how to do this?
This is some really bad issue for a lot of users => why do you close this instantly whithout any help?

Real world case is : Admin gets an excel sheet regularly by a 2nd company. There is no possible way to make the 2nd company work with en_us formulae. Admin needs to read in the file.

- so now - lost ? Because we are not in America?
Sorry if this sounds harsh, but I just hate this typical american behaviour. really.

**Comment by p1ngb4ck** [comment]
this is just sooooooooooooooooo fuckin stupid to just close this without a single bit of help

**Comment by MAKS-dev** [comment]
Sorry to jump in here, but MarkBaker did answer your question. Even when it was a support/usage question and it should have been asked on StackOverflow or Gitter.

To explain his answer a little more:
You are using a German function "SVERWEIS", that does not exist in the library. There is a website which you can use to find the English function name:
http://www.excelfunctions.eu/SVERWEIS/German-English

So your formula should be something like this:
`=VLOOKUP(E3, Tabelle1!$B:$D;3, FALSE)`

It's just a little stupid (sorry for this reference) to expect PhpSpreadsheet to include every possible Excel language. A program language is in English. In PHP you also use English names and notation like the dot as decimal point. Nothing to do with America, just how things are. (I'm Dutch myself by the way)

If you need additional help, just go to StackOverflow or Gitter.
Cheers

**Comment by p1ngb4ck** [comment]
It should not have been asked on StackOverflow or Gitter - because it is not mentioned in the f****** docs - which is (if it`s about such a typical default use-case) a bug for itself.
That`s why asking for it here is completely correct.
The underlying error is not the local function naming, but the missing routine for matrix-based references.

Example : xlsx contains a row with fields A and B. A contains a numeric ID. B contains a reference to a field in a second worksheet using the value of A for the reference.
The second worksheet has e.g. multiple rows and columns A to I.
The reference looks like this (I specifically use translated en_us formulae notation, of course, so you see the german variant is just NOT the problem) :

=VLOOKUP(A,Sheet2!A:I;2;FALSE)

The above formulae should be valid, but leads to an error during getCalculatedValue() - due to the function expecting a column index behind the "A" of Sheet2 - which is just not there if a matrix notation is used.
![PHPSpreadSheetError](https://user-images.githubusercontent.com/588481/66831420-e4b87d80-ef57-11e9-9321-893fe3ca4da9.PNG)

Also : if phpspreadsheet actually expects absolute notation in getCalculatedValue() -> this is quite insane - in the real world, normal Excel users will never use that notation - shall I rewrite each file in Excel manually, to be sure it can be read?

**Comment by lodzen** [comment]
Thanks @p1ngb4ck This is exactly the issue. The function is correctly translated in the en_us format but the $ in the matrix is causing the issue.

**Comment by p1ngb4ck** [comment]
Also : I apologize for my (indeed) rude behaviour. Maybe you can forgive me - I am extremely frustrated right now, because from my PoV, these use-cases will be coming up a lot more in the real world, than many many other tiny things, which are being taken care of fine - while essential default functionality is not present.
This just cost me several hours, while bein in business context and having to parse a "simple" excel sheet - maybe you can understand this just sucks - because there is no doc about all this.

Please focus more on reading files in the docs - this is the most common usecase.

**Comment by p1ngb4ck** [comment]
@lodzen : no it is not the $ - it is just not able to read a matrix in a VLOOKUP in general -
currently I suppose, we need to go around all this manually, by reading in the second worksheet in advance -> build a custom array -> manually read all formulae -> stripe the necessary field data manually from the VLOOKUP - ref, then use those to lookup the correct cell value from the previously built custom array.


 .... makes me going nuts right now, tbh
