### ISSUE TITLE
SUMIF formula is not working

### ISSUE THREAD

**Issue by chatis** [PHPOffice/PhpSpreadsheet#892]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I tried to add the formula =SUMIF, but this is not working. An error occure and the formula is deleted when I open the excel file

### What is the current behavior?

When the code try to calculate the formula, this is bugging

### What are the steps to reproduce?

[sumif.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2880666/sumif.xlsx)

```php
<?php require 'vendor/autoload.php';

set_time_limit(-1);
//error_reporting(0);
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader("Xlsx");
$objPHPExcel = $reader->load("sumif.xlsx");
$objPHPExcel->setActiveSheetIndex(1);

for($count = 1 ; $count <= 10; $count++)
{
	$objPHPExcel->getActiveSheet()->setCellValue('D'.$count, '=SUMIF(Résumé!D$2:D$22;B'.$count.';Résumé!F$2:F$22)');
}

$objPHPExcel->setActiveSheetIndex(0);

header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="paiement_'.date('Y-m-d').'.xlsx"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header ('Pragma: public'); // HTTP/1.0
/**/
$objWriter = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($objPHPExcel);
$objWriter->setPreCalculateFormulas(false);
$objWriter->save('php://output');
/**/
?>
```

### Which versions of PhpSpreadsheet and PHP are affected?

PHP 7.0 and PhpSpreadsheet 1.6.0

**Comment by chatis** [comment]
Is someone has an idea why ? I'm really in a blocked situation.... Thank you

**Comment by MarkBaker** [comment]
When entering formulae, en_us settings apply, as described in [the docs](https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#write-a-formula-into-a-cell):

- Decimal separator is . (period)
- Function argument separator is , (comma)
- Matrix row separator is ; (semicolon)
- English function names must be used

Unless you have specified a locale-setting, as described in [the docs](https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#locale-settings-for-formulae)

And your formula is using `;` as a function argument separator rather than a `,`

**Comment by chatis** [comment]
I'm really sorry ! Thank you
