### ISSUE TITLE
have tried and tested your example yourself ? 

### ISSUE THREAD

**Issue by Tyraan** [PHPOffice/PhpSpreadsheet#896]
have you tried  your example in your  document  ??

**Comment by Tyraan** [comment]
in your doc :
https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Reader/11_Reading_a_workbook_in_chunks_using_a_configurable_read_filter_(version_1).php


are you sure your example will function as you said “  // Load only the rows that match our filter from $inputFileName ”  when you use it to import a FUCKING single sheet excel.xslx

ARE YOU????????

I've tried  many times find out that your example code will make varialble $spreadsheet   a  larger and larger data array after each for loop. This is really frustrating .

please test your code .

**Comment by damijanc** [comment]
Since you are already looking into the issue, maybe you can provide a fix in a pull request?

**Comment by damijanc** [comment]
And please restrain yourself from using sware words in issues. The project is open source and maintained by volunteers, so feel free to fork it.

**Comment by Tyraan** [comment]
> Since you are already looking into the issue, maybe you can provide a fix in a pull request?
I have said , try the example code to load  a  simple .xlsx with $chunkFilter obj   file and you will find it.
This bug is too simple too belive it can happen.

**Comment by damijanc** [comment]
If it is so simple why not help the community and provide a pull request with a fix? This is probably the fastest way to get the fix into the project.

**Comment by Tyraan** [comment]
> If it is so simple why not help the community and provide a pull request with a fix? This is probably the fastest way to get the fix into the project.

do not mix the concept , I am very angry because the bug is totally do not match  the great energy and time that I wasted on it.  Do unittest before you publish the code , CAN YOU ????????

**Comment by damijanc** [comment]
to get your point, you are mad because the stuff you use for free does not work for you. You really have no idea what is the point of open source. Let me give you a hint: 

> It is not free developers that will work on my problems.<

**Comment by Tyraan** [comment]
> to get your point, you are mad because the stuff you use for free does not work for you. You really have no idea what is the point of open source. Let me give you a hint:
> 
> > It is not free developers that will work on my problems.

Then I must say that you completely misunderstood my point .
1, open source is not an excuse for not doing unit testing,
2, Release  junk code to this world is a sinister crime, and put the untested code into the document which misleading the developers is even more guilty, they should be hanged.
3. I don't expect my problem to be solved here, I just beg you PLEASE DO NOT  CREATE TROUBLES for developers.  Nobody shall be waste life.
4, I'm not mad, I'm angry. because the document LIE TO ME.

ps: just DO UNITTEST , OK?

**Comment by damijanc** [comment]
I am not the maintainer of the project, just to be clear. The code is maintained by someone, who does it in his own free time. Documentation is maintained by someone in his free time. So instead of being pissed why don't you help the community and submit fixes for documentation and the code?

This way the community will have accurate documentation and working code and you have helped the next person. This is my point and that is the point of open source - COLLABORATION.

Being angry is an irrational emotion and it is not helping you or the community.

**Comment by psihius** [comment]
People, don't feed the troll, I understand you want to teach etiquette and stuff, but c'mon, it's internet and I hope it's not everyone's first rodeo.
Just report him and be done with it. Also, if you believe his profile - it's Chinese and there are certain cultural types that have no shame and care about anything, so your efforts are futile :)

**Comment by MarkBaker** [comment]
First off, what bug? Second, would you really trust a sinister criminal to fix a bug? Third, if it is a bug and you hang me, it won't be fixed

**Comment by thomasesmith** [comment]
> NO WARRANTY
> 
>   15. BECAUSE THE LIBRARY IS LICENSED FREE OF CHARGE, THERE IS NO
> WARRANTY FOR THE LIBRARY, TO THE EXTENT PERMITTED BY APPLICABLE LAW.
> EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR
> OTHER PARTIES PROVIDE THE LIBRARY "AS IS" WITHOUT WARRANTY OF ANY
> KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE
> IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
> PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE
> LIBRARY IS WITH YOU.  SHOULD THE LIBRARY PROVE DEFECTIVE, YOU ASSUME
> THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

**Comment by MarkBaker** [comment]
The data array generated in `$sheetData = $spreadsheet->getActiveSheet()->toArray(null, true, true, true);` always begins at cell A1. That does not mean that cells are loaded that shouldn't be loaded (that would be a bug); but that the array contains empty values between cell A1 and the range that has been loaded. Yes, the example would be better if it used `rangeToArray()` instead of `toArray()`, but to suggest that I should be hanged for the sinister crime of not being absolutely clear in a sample code is a bit extreme.

I've had death threats before when I've threatened to push minimum PHP versions, but never before has anybody suggested that my life should be terminated over a bug, when it isn't actually a bug.

**Comment by djallits** [comment]
I just want to add that the OP originally chose to use this package either without evaluating the actual code or disregarded there wasn’t test coverage. In either case, the OP owns the issue here.
