### ISSUE TITLE
Documentation URL fix (/en/develop --> /en/latest)

### ISSUE THREAD

**Issue by sprise** [PHPOffice/PhpSpreadsheet#909]
This is:

```
- [* ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Load anticipated DOCS page linked by search.

### What is the current behavior?
404

### What are the steps to reproduce?
See this link: https://phpspreadsheet.readthedocs.io/en/develop/topics/accessing-cells/ found through search. 

### Which versions of PhpSpreadsheet and PHP are affected?
Presumably this should be as easy as creating a redirect for /en/develop/$1 URLs that goes to /en/latest/$1

**Comment by oleibman** [comment]
@PowerKiKi This is a very old, and not terribly pressing, issue. But the link mentioned by the reporter still exists, and is still broken (no styling, nothing happens when you click on the hyperlinks). It seems fairly simple to add a redirect using the project dashboard at readthedocs if it considers you a project owner, which it does for you but not for me. Is adding the redirect for "develop" something you can take care of?
