### ISSUE TITLE
getHighestRow not right after removed some rows

### ISSUE THREAD

**Issue by ebuildy** [PHPOffice/PhpSpreadsheet#943]
This is:

```
- [X] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Removing rows should refresh ``cachedHighestRow``.

### What is the current behavior?

getHighestRow gives the same result before and after have removed some rows.

### What are the steps to reproduce?

```
$rowEnd1 = $this->worksheet->getHighestRow();
$this->worksheet->removeRow(0, 10);
$rowEnd2 = $this->worksheet->getHighestRow();

assertTrue($rowEnd1, $rowEnd2);
```

### Which versions of PhpSpreadsheet and PHP are affected?

* php 7.2
* PhpSpreadsheet 1.6.0

**Comment by mikehaertl** [comment]
I have a similar issue. I removed lines from a document with LibreOffice. Afterwards `getHighestRow()` returns a way to large value ( `1048576` in my case for a file with only 4 lines).

And a word about this "stale bot": Why are you closing issues without any feedback? I would understand if you asked a question and the issue opener did not respond anymore. But this here is very weird: The maintainers did not react and after a while the issue was closed - but it's still not solved.

You shy away people that want to help improve this library. I'd strongly suggest to reconsider this behavior.

**Comment by khayyak** [comment]
I have similar issue , and I have two solutions :
 First : when you delete old rows from XLSX file you should not delete normally with delete button , you should delete it using delete option in the top right of excel file .
Second one : you can check if a required cell is null or whole row is null like that :

for($row = 2 ; $row <= $lastRow ; $row++)
        {
            if($page->getCell('A'.$row)->getValue() == NULL && $page->getCell('B'.$row)->getValue() == NULL)
            {
                break;
                //or continue or anything you want;
            }
            else
            {
              // your logic
            }
}

hope that helps you or help someone need it.

**Comment by oleibman** [comment]
My testing indicates that the problem as reported is now solved; ditto for columns. However, the results aren't satisfactory if the delete range overlaps the high row or column. And deleting a non-positive number of rows or columns is permitted for some reason, but the semantics aren't defined. So, I will reopen this issue while I consider my options.
