### ISSUE TITLE
A package performance issue

### ISSUE THREAD

**Issue by DarkNami** [PHPOffice/PhpSpreadsheet#949]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the current behavior?

(My English isn't very good, please don't mind.)

Recently, I installed PHPOffice/PhpSpreadsheet in my little project.
A few days later, I perceived my app response time significantly increased, from '3xx ms' increased to '1xxx ms' each request.

I debugged and found the reason: 'composer autoload spend 600ms to load markbaker/complex and markbaker/matrix'.

Ref: MarkBaker/PHPComplex#8

### What are the steps to reproduce?

```php
<?php
require __DIR__ . '/vendor/autoload.php';
?>
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.6.0, PHP 7.1

![autoload](https://user-images.githubusercontent.com/5100919/55311288-14f56e80-5495-11e9-8008-fac3b194c9f6.png)

**Comment by DarkNami** [comment]
Affected by open_basedir is On:
https://bugs.php.net/bug.php?id=52312

**Comment by oleibman** [comment]
markbaker/complex V3 and markbaker/matrix V3, released in 2021 and in use by PhpSpreadsheet since then, greatly reduced the number of modules in each vs. V2, and eliminated the autoload of the functions in composer.json. I imagine that fixed this problem. Leaving the issue closed, removing stale label.
